var charater = 'sorcerer';
var skill = [];

// Wintry Armor
skill.push({"id":"none","name":"IcyShield","name_l10n":"Wintry Armor","skill_tag":"Buff","lvl":"3","type":"default","condition":"null","desc":"For [%e1.Reflector.RemainTime], reflects [%e1.Reflector.FixedDamage] damage back to an enemy within [%e1.Reflector.MaxRange]m who [%e1.Reflector.Condition]s you, and decreases the enemy's movement speed and attack speed for [%e2.Provoker.OtherSkill.e1.Snare.RemainTime].","action":"self","prepare":"instance","cd":"183600","skill_type":"Magical","skill_sub_type":"Buff","lvls":[{"cost":{"type":"MP","value":"430","timer":0},"rules":{"[%e1.Reflector.FixedDamage]":"700","[%e1.Reflector.MaxRange]":"5","[%e1.Reflector.Condition]":"all attack","[%e1.Reflector.RemainTime]":"15 sec ","[%e2.Provoker.OtherSkill.e1.Snare.RemainTime]":"2 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"730","timer":0},"rules":{"[%e1.Reflector.FixedDamage]":"1 000","[%e1.Reflector.MaxRange]":"5","[%e1.Reflector.Condition]":"all attack","[%e1.Reflector.RemainTime]":"15 sec ","[%e2.Provoker.OtherSkill.e1.Snare.RemainTime]":"2 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"1030","timer":0},"rules":{"[%e1.Reflector.FixedDamage]":"1 300","[%e1.Reflector.MaxRange]":"5","[%e1.Reflector.Condition]":"all attack","[%e1.Reflector.RemainTime]":"15 sec ","[%e2.Provoker.OtherSkill.e1.Snare.RemainTime]":"2 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}}]});

// Glacial Shard
skill.push({"id":"none","name":"ZeroPoint","name_l10n":"Glacial Shard","skill_tag":"Attack","lvl":"3","type":"default","condition":"null","desc":"Inflicts [%e1.SpellATK_Instant.FixDamage] magical water damage on a target within [%First_Target_Valid_Distance]m.","action":"target","prepare":"4000","cd":"60600","skill_type":"Magical","skill_sub_type":"Attack","pvp_damage":"65","lvls":[{"cost":{"type":"MP","value":"1077","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"3 872","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-600","param":"cd"}},{"cost":{"type":"MP","value":"1377","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"4 104","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-600","param":"cd"}},{"cost":{"type":"MP","value":"1677","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"4 335","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-600","param":"cd"}}]});

// Sleeping Storm
skill.push({"id":"none","name":"SleepingStorm","name_l10n":"Sleeping Storm","skill_tag":"Sleep","lvl":"1","type":"default","condition":"null","desc":"Puts a target within [%First_Target_Valid_Distance]m and up to 6 enemies within 12m of the target to sleep for [%e1.Sleep.RemainTime] and increases their [%e2.StatUp.StatName].","action":"zone","prepare":"1000","cd":"183600","skill_type":"Magical","skill_sub_type":"Debuff","pvp_time":"40","lvls":[{"cost":{"type":"MP","value":"602","timer":0},"rules":{"[%First_Target_Valid_Distance]":"25","[%e2.StatUp.StatName]":"All Elemental Defence","[%e1.Sleep.RemainTime]":"20 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}}]});

// Wind Cut Down
skill.push({"id":"none","name":"WindCutter","name_l10n":"Wind Cut Down","skill_tag":"Abnormal Condition","lvl":"6","type":"default","condition":"null","desc":"Inflicts [%e1.SpellATK_Instant.FixDamage] magical wind damage on a target within [%First_Target_Valid_Distance]m, and decreases [%e2.StatDown.StatName] by [%e2.StatDown.Value] for [%e2.StatDown.RandomTime] - [%e2.StatDown.RemainTime].","action":"target","prepare":"1000","cd":"24000","skill_type":"Magical","skill_sub_type":"Attack","lvls":[{"cost":{"type":"MP","value":"202","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"853","[%e2.StatDown.StatName]":"Magical Acc","[%e2.StatDown.Value]":"200","[%e2.StatDown.RandomTime]":5,"[%e2.StatDown.RemainTime]":"7 sec ","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-6","param":"cost"}},{"cost":{"type":"MP","value":"224","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"913","[%e2.StatDown.StatName]":"Magical Acc","[%e2.StatDown.Value]":"230","[%e2.StatDown.RandomTime]":5,"[%e2.StatDown.RemainTime]":"7 sec ","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-7","param":"cost"}},{"cost":{"type":"MP","value":"265","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"973","[%e2.StatDown.StatName]":"Magical Acc","[%e2.StatDown.Value]":"260","[%e2.StatDown.RandomTime]":5,"[%e2.StatDown.RemainTime]":"7 sec ","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-8","param":"cost"}},{"cost":{"type":"MP","value":"296","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"1 033","[%e2.StatDown.StatName]":"Magical Acc","[%e2.StatDown.Value]":"290","[%e2.StatDown.RandomTime]":5,"[%e2.StatDown.RemainTime]":"7 sec ","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-9","param":"cost"}},{"cost":{"type":"MP","value":"344","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"1 093","[%e2.StatDown.StatName]":"Magical Acc","[%e2.StatDown.Value]":"320","[%e2.StatDown.RandomTime]":5,"[%e2.StatDown.RemainTime]":"7 sec ","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-10","param":"cost"}},{"cost":{"type":"MP","value":"424","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"1 154","[%e2.StatDown.StatName]":"Magical Acc","[%e2.StatDown.Value]":"350","[%e2.StatDown.RandomTime]":5,"[%e2.StatDown.RemainTime]":"7 sec ","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-12","param":"cost"}}]});

// Illusion Storm
skill.push({"id":"none","name":"IllusionStorm","name_l10n":"Illusion Storm","skill_tag":"Stun","lvl":"6","type":"default","condition":"null","desc":"Inflicts [%e1.SpellATK_Instant.FixDamage] magical fire damage on up to 6 targets within 10m. The target is stunned for [%e2.Stun.RemainTime].","action":"around","prepare":"instance","cd":"183600","skill_type":"Magical","skill_sub_type":"Attack","lvls":[{"cost":{"type":"MP","value":"146","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"547","[%e2.Stun.RemainTime]":"4 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"286","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"586","[%e2.Stun.RemainTime]":"4 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"426","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"624","[%e2.Stun.RemainTime]":"4 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"566","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"663","[%e2.Stun.RemainTime]":"4 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"706","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"701","[%e2.Stun.RemainTime]":"4 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"846","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"740","[%e2.Stun.RemainTime]":"4 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}}]});

// Flame Spray
skill.push({"id":"none","name":"FlameStrike","name_l10n":"Flame Spray","skill_tag":"Attack","lvl":"6","type":"default","condition":"null","desc":"Inflicts [%e1.SpellATK_Instant.FixDamage] magical fire damage on a target within [%First_Target_Valid_Distance]m.","action":"target","prepare":"3500","cd":"30000","skill_type":"Magical","skill_sub_type":"Attack","pvp_damage":"70","lvls":[{"cost":{"type":"MP","value":"939","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"2 520","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-27","param":"cost"}},{"cost":{"type":"MP","value":"1032","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"2 697","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-30","param":"cost"}},{"cost":{"type":"MP","value":"1125","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"2 874","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-33","param":"cost"}},{"cost":{"type":"MP","value":"1237","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"3 051","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-35","param":"cost"}},{"cost":{"type":"MP","value":"1310","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"3 228","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-38","param":"cost"}},{"cost":{"type":"MP","value":"1403","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"3 404","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-41","param":"cost"}}]});

// Manifest Tornado
skill.push({"id":"none","name":"Light_SummonTornado","name_l10n":"Manifest Tornado","skill_tag":"Stun","lvl":"8","type":"default","condition":"null","desc":"Summons a tornado that remains on a spot within [%First_Target_Valid_Distance]m for [%e1.SummonSkillArea.SummonTime]. It inflicts continuous magical wind damage on up to 6 enemies within 10m and stuns them briefly.","action":"target","prepare":"instance","cd":"183600","skill_type":"Magical","skill_sub_type":"Attack","lvls":[{"cost":{"type":"MP","value":"107","timer":0},"rules":{"[%First_Target_Valid_Distance]":"15","[%e1.SummonSkillArea.SummonTime]":"3 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"211","timer":0},"rules":{"[%First_Target_Valid_Distance]":"15","[%e1.SummonSkillArea.SummonTime]":"3 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"315","timer":0},"rules":{"[%First_Target_Valid_Distance]":"15","[%e1.SummonSkillArea.SummonTime]":"3 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"419","timer":0},"rules":{"[%First_Target_Valid_Distance]":"15","[%e1.SummonSkillArea.SummonTime]":"3 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"523","timer":0},"rules":{"[%First_Target_Valid_Distance]":"15","[%e1.SummonSkillArea.SummonTime]":"3 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"627","timer":0},"rules":{"[%First_Target_Valid_Distance]":"15","[%e1.SummonSkillArea.SummonTime]":"3 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"731","timer":0},"rules":{"[%First_Target_Valid_Distance]":"15","[%e1.SummonSkillArea.SummonTime]":"3 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"835","timer":0},"rules":{"[%First_Target_Valid_Distance]":"15","[%e1.SummonSkillArea.SummonTime]":"3 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}}]});

// Summon Rock
skill.push({"id":"none","name":"RockFall","name_l10n":"Summon Rock","skill_tag":"Attack","lvl":"6","type":"default","condition":"null","desc":"Inflicts [%e1.SpellATK_Instant.FixDamage] magical earth damage on a target within [%First_Target_Valid_Distance]m.","action":"target","prepare":"instance","cd":"90900","skill_type":"Magical","skill_sub_type":"Attack","pvp_damage":"80","lvls":[{"cost":{"type":"MP","value":"137","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"841","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-900","param":"cd"}},{"cost":{"type":"MP","value":"237","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"900","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-900","param":"cd"}},{"cost":{"type":"MP","value":"337","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"959","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-900","param":"cd"}},{"cost":{"type":"MP","value":"437","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"1 018","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-900","param":"cd"}},{"cost":{"type":"MP","value":"537","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"1 077","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-900","param":"cd"}},{"cost":{"type":"MP","value":"637","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"1 136","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-900","param":"cd"}}]});

// Curse of Weakness
skill.push({"id":"none","name":"CounterMagic","name_l10n":"Curse of Weakness","skill_tag":"Abnormal Condition","lvl":"8","type":"default","condition":"null","desc":"Each time the target within [%First_Target_Valid_Distance]m uses magical skills, magical damage equal to [%e1.MagicCounterATK.Damage]%% of the target's MAX HP is inflicted on the target for [%e1.MagicCounterATK.RemainTime]. Magical damage cannot exceed [%e1.MagicCounterATK.MaxDamage].","action":"target","prepare":"instance","cd":"306000","skill_type":"Magical","skill_sub_type":"Debuff","lvls":[{"cost":{"type":"MP","value":"61","timer":0},"rules":{"[%e1.MagicCounterATK.Damage]%":"12","[%First_Target_Valid_Distance]":"25","[%e1.MagicCounterATK.MaxDamage]":"605","[%e1.MagicCounterATK.RemainTime]":"1 min"},"lv_up":{"type":"cd","value":"-6000","param":"cd"}},{"cost":{"type":"MP","value":"91","timer":0},"rules":{"[%e1.MagicCounterATK.Damage]%":"12","[%First_Target_Valid_Distance]":"25","[%e1.MagicCounterATK.MaxDamage]":"719","[%e1.MagicCounterATK.RemainTime]":"1 min"},"lv_up":{"type":"cd","value":"-6000","param":"cd"}},{"cost":{"type":"MP","value":"121","timer":0},"rules":{"[%e1.MagicCounterATK.Damage]%":"12","[%First_Target_Valid_Distance]":"25","[%e1.MagicCounterATK.MaxDamage]":"832","[%e1.MagicCounterATK.RemainTime]":"1 min"},"lv_up":{"type":"cd","value":"-6000","param":"cd"}},{"cost":{"type":"MP","value":"151","timer":0},"rules":{"[%e1.MagicCounterATK.Damage]%":"12","[%First_Target_Valid_Distance]":"25","[%e1.MagicCounterATK.MaxDamage]":"946","[%e1.MagicCounterATK.RemainTime]":"1 min"},"lv_up":{"type":"cd","value":"-6000","param":"cd"}},{"cost":{"type":"MP","value":"181","timer":0},"rules":{"[%e1.MagicCounterATK.Damage]%":"12","[%First_Target_Valid_Distance]":"25","[%e1.MagicCounterATK.MaxDamage]":"1 059","[%e1.MagicCounterATK.RemainTime]":"1 min"},"lv_up":{"type":"cd","value":"-6000","param":"cd"}},{"cost":{"type":"MP","value":"211","timer":0},"rules":{"[%e1.MagicCounterATK.Damage]%":"12","[%First_Target_Valid_Distance]":"25","[%e1.MagicCounterATK.MaxDamage]":"1 173","[%e1.MagicCounterATK.RemainTime]":"1 min"},"lv_up":{"type":"cd","value":"-6000","param":"cd"}},{"cost":{"type":"MP","value":"241","timer":0},"rules":{"[%e1.MagicCounterATK.Damage]%":"12","[%First_Target_Valid_Distance]":"25","[%e1.MagicCounterATK.MaxDamage]":"1 287","[%e1.MagicCounterATK.RemainTime]":"1 min"},"lv_up":{"type":"cd","value":"-6000","param":"cd"}},{"cost":{"type":"MP","value":"271","timer":0},"rules":{"[%e1.MagicCounterATK.Damage]%":"12","[%First_Target_Valid_Distance]":"25","[%e1.MagicCounterATK.MaxDamage]":"1 400","[%e1.MagicCounterATK.RemainTime]":"1 min"},"lv_up":{"type":"cd","value":"-6000","param":"cd"}}]});

// Exchange Vitality
skill.push({"id":"none","name":"HPMPExchange","name_l10n":"Exchange Vitality","skill_tag":"Attack","lvl":"1","type":"default","condition":"null","desc":"Exchanges your current HP with your MP.","action":"self","prepare":"instance","cd":"306000","skill_type":"Magical","skill_sub_type":"Heal","lvls":[{"cost":"none","rules":[],"lv_up":{"type":"cd","value":"-6000","param":"cd"}}]});

// Ice Sheet
skill.push({"id":"none","name":"Light_FrostPillar","name_l10n":"Ice Sheet","skill_tag":"Abnormal Condition","lvl":"8","type":"default","condition":"null","desc":"Inflicts magical water damage on up to 8 enemies around the selected spot and reduces their movement speed for 20 seconds.","action":"point","prepare":"instance","cd":"183600","skill_type":"Magical","skill_sub_type":"Attack","lvls":[{"cost":{"type":"MP","value":"111","timer":0},"rules":[],"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"151","timer":0},"rules":[],"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"191","timer":0},"rules":[],"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"231","timer":0},"rules":[],"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"271","timer":0},"rules":[],"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"311","timer":0},"rules":[],"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"351","timer":0},"rules":[],"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":{"type":"MP","value":"391","timer":0},"rules":[],"lv_up":{"type":"cd","value":"-3600","param":"cd"}}]});

// Storm Strike
skill.push({"id":"none","name":"CycloneStrike","name_l10n":"Storm Strike","skill_tag":"Attack","lvl":"8","type":"default","condition":"null","desc":"Inflicts [%e1.SpellATK_Instant.FixDamage] magical wind damage on a target within [%First_Target_Valid_Distance]m.","action":"target","prepare":"4000","cd":"122400","skill_type":"Magical","skill_sub_type":"Attack","pvp_damage":"50","lvls":[{"cost":{"type":"MP","value":"170","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"2 286","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-2400","param":"cd"}},{"cost":{"type":"MP","value":"280","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"2 716","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-2400","param":"cd"}},{"cost":{"type":"MP","value":"390","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"3 145","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-2400","param":"cd"}},{"cost":{"type":"MP","value":"500","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"3 574","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-2400","param":"cd"}},{"cost":{"type":"MP","value":"610","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"4 004","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-2400","param":"cd"}},{"cost":{"type":"MP","value":"720","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"4 433","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-2400","param":"cd"}},{"cost":{"type":"MP","value":"830","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"4 862","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-2400","param":"cd"}},{"cost":{"type":"MP","value":"940","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"5 292","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-2400","param":"cd"}}]});

// Elemental Ward
skill.push({"id":"none","name":"ElementalSeal","name_l10n":"Elemental Ward","skill_tag":"Buff","lvl":"1","type":"default","condition":"null","desc":"Increases your [%e1.StatUp.StatName]  by [%e1.StatUp.Value] and your [%e2.StatUp.StatName] by [%e2.StatUp.Value] for [%e1.StatUp.RemainTime].","action":"self","prepare":"instance","cd":"183600","skill_type":"Magical","skill_sub_type":"Buff","lvls":[{"cost":{"type":"MP","value":"326","timer":0},"rules":{"[%e1.StatUp.StatName]":"All Elemental Defence","[%e1.StatUp.Value]":"300","[%e2.StatUp.StatName]":"Magic Resist","[%e2.StatUp.Value]":"300","[%e1.StatUp.RemainTime]":"1 min"},"lv_up":{"type":"cd","value":"-3600","param":"cd"}}]});

// Ice Harpoon
skill.push({"id":"none","name":"Stigma_IceLance","name_l10n":"Ice Harpoon","skill_tag":"Attack","lvl":"8","type":"default","condition":"null","desc":"Inflicts [%e1.SpellATK_Instant.FixDamage] magical water damage on a target within [%First_Target_Valid_Distance]m.","action":"target","prepare":"2500","cd":"6000","skill_type":"Magical","skill_sub_type":"Attack","lvls":[{"cost":{"type":"MP","value":"64","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"682","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-2","param":"cost"}},{"cost":{"type":"MP","value":"123","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"810","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-4","param":"cost"}},{"cost":{"type":"MP","value":"181","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"938","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-5","param":"cost"}},{"cost":{"type":"MP","value":"240","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"1 066","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-7","param":"cost"}},{"cost":{"type":"MP","value":"299","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"1 194","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-9","param":"cost"}},{"cost":{"type":"MP","value":"357","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"1 322","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-10","param":"cost"}},{"cost":{"type":"MP","value":"416","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"1 450","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-12","param":"cost"}},{"cost":{"type":"MP","value":"475","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"1 578","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"MP","value":"-14","param":"cost"}}]});

// Boon of Quickness
skill.push({"id":"none","name":"Dark_icyVeins","name_l10n":"Boon of Quickness","skill_tag":"Buff","lvl":"1","type":"default","condition":"null","desc":"Reduces the casting time of all your magic skills by [%e1.BoostSkillCastingTime.CastingBonus]%% for [%e1.BoostSkillCastingTime.RemainTime].","action":"self","prepare":"instance","cd":"300000","skill_type":"Magical","skill_sub_type":"Buff","lvls":[{"cost":{"type":"MP","value":"207","timer":0},"rules":{"[%e1.BoostSkillCastingTime.CastingBonus]%":"50","[%e1.BoostSkillCastingTime.RemainTime]":"15 sec "},"lv_up":{"type":"MP","value":"-6","param":"cost"}}]});

// Absolute Zero
skill.push({"id":"none","name":"Hibernation","name_l10n":"Absolute Zero","skill_tag":"Stun","lvl":"1","type":"default","condition":"null","desc":"Freezes a target within [%First_Target_Valid_Distance]m to stun it and make it unable to be attacked for [%e1.stun.RandomTime] - [%e1.stun.RemainTime].","action":"target","prepare":"instance","cd":"183600","skill_type":"Magical","skill_sub_type":"Debuff","pvp_time":"80","lvls":[{"cost":{"type":"MP","value":"1054","timer":0},"rules":{"[%First_Target_Valid_Distance]":"20","[%e1.stun.RandomTime]":"6","[%e1.stun.RemainTime]":"8 sec "},"lv_up":{"type":"cd","value":"-3600","param":"cd"}}]});

// Arcane Thunderbolt
skill.push({"id":"none","name":"StormShock","name_l10n":"Arcane Thunderbolt","skill_tag":"Attack","lvl":"8","type":"default","condition":"null","desc":"Inflicts [%e1.SpellATK_Instant.FixDamage] magical wind damage on a target within [%First_Target_Valid_Distance]m and stuns the target for a short time.","action":"target","prepare":"1000","cd":"153000","skill_type":"Magical","skill_sub_type":"Attack","lvls":[{"cost":{"type":"MP","value":"90","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"801","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-3000","param":"cd"}},{"cost":{"type":"MP","value":"176","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"858","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-3000","param":"cd"}},{"cost":{"type":"MP","value":"262","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"914","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-3000","param":"cd"}},{"cost":{"type":"MP","value":"348","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"970","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-3000","param":"cd"}},{"cost":{"type":"MP","value":"434","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"1 027","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-3000","param":"cd"}},{"cost":{"type":"MP","value":"520","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"1 083","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-3000","param":"cd"}},{"cost":{"type":"MP","value":"600","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"1 103","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-3000","param":"cd"}},{"cost":{"type":"MP","value":"650","timer":0},"rules":{"[%e1.SpellATK_Instant.FixDamage]":"1 183","[%First_Target_Valid_Distance]":"25"},"lv_up":{"type":"cd","value":"-3000","param":"cd"}}]});

// Slumberswept Wind
skill.push({"id":"none","name":"windsleep","name_l10n":"Slumberswept Wind","skill_tag":"Sleep","lvl":"3","type":"default","condition":"null","desc":"Puts up to 6 enemies within 12m to sleep for [%e2.Sleep.RemainTime] and increases their [%e3.StatUp.StatName].","action":"around","prepare":"instance","cd":"306000","skill_type":"Magical","skill_sub_type":"Debuff","pvp_time":"40","lvls":[{"cost":{"type":"MP","value":"830","timer":0},"rules":{"[%e3.StatUp.StatName]":"All Elemental Defence","[%e2.Sleep.RemainTime]":"10 sec "},"lv_up":{"type":"cd","value":"-6000","param":"cd"}},{"cost":{"type":"MP","value":"930","timer":0},"rules":{"[%e3.StatUp.StatName]":"All Elemental Defence","[%e2.Sleep.RemainTime]":"15 sec "},"lv_up":{"type":"cd","value":"-6000","param":"cd"}},{"cost":{"type":"MP","value":"1030","timer":0},"rules":{"[%e3.StatUp.StatName]":"All Elemental Defence","[%e2.Sleep.RemainTime]":"20 sec "},"lv_up":{"type":"cd","value":"-6000","param":"cd"}}]});

// Aetherblaze
skill.push({"id":"none","name":"FireShield","name_l10n":"Aetherblaze","skill_tag":"Buff","lvl":"3","type":"default","condition":"null","desc":"Increases your magical attack by [%e1.BoostSpellAttackEffect.EffectBonus1]%% and decreases MP consumption by [%e2.BoostSkillCost.BonusRate]%% for 15 seconds.","action":"self","prepare":"instance","cd":"183600","skill_type":"Magical","skill_sub_type":"Buff","lvls":[{"cost":"none","rules":{"[%e1.BoostSpellAttackEffect.EffectBonus1]%":"9","[%e2.BoostSkillCost.BonusRate]%":"20"},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":"none","rules":{"[%e1.BoostSpellAttackEffect.EffectBonus1]%":"12","[%e2.BoostSkillCost.BonusRate]%":"20"},"lv_up":{"type":"cd","value":"-3600","param":"cd"}},{"cost":"none","rules":{"[%e1.BoostSpellAttackEffect.EffectBonus1]%":"15","[%e2.BoostSkillCost.BonusRate]%":"20"},"lv_up":{"type":"cd","value":"-3600","param":"cd"}}]});

// Repulsion Field
skill.push({"id":"none","name":"stoneBarrier","name_l10n":"Repulsion Field","skill_tag":"Special","lvl":"3","type":"default","condition":"null","desc":"Immobilizes you within a shield for [%e1.Shield.RemainTime] that blocks [%e1.Shield.CoverValue] damage each time you receive [%e1.Shield.Condition].","action":"self","prepare":"instance","cd":"306000","skill_type":"Magical","skill_sub_type":"Buff","lvls":[{"cost":{"type":"MP","value":"830","timer":0},"rules":{"[%e1.Shield.CoverValue]":"30 000","[%e1.Shield.Condition]":"all attack","[%e1.Shield.RemainTime]":"6 sec "},"lv_up":{"type":"cd","value":"-6000","param":"cd"}},{"cost":{"type":"MP","value":"930","timer":0},"rules":{"[%e1.Shield.CoverValue]":"40 000","[%e1.Shield.Condition]":"all attack","[%e1.Shield.RemainTime]":"6 sec "},"lv_up":{"type":"cd","value":"-6000","param":"cd"}},{"cost":{"type":"MP","value":"1030","timer":0},"rules":{"[%e1.Shield.CoverValue]":"50 000","[%e1.Shield.Condition]":"all attack","[%e1.Shield.RemainTime]":"6 sec "},"lv_up":{"type":"cd","value":"-6000","param":"cd"}}]});
