// Українська локалізація калькулятора стигм.
//
// Назви вмінь узято з українського паку Origin (client_strings_skill.xml)
// за іменем рядка STR_..., а не перекладено наново — так вони збігаються
// з тим, що гравець бачить у клієнті.
//
// Описи вмінь узято з українського паку Riftshade (client_strings_skill.xml):
// його версія найближча до 4.6, тож id вмінь збігаються майже повністю.
//
// Файл підключається ПІСЛЯ lang_en.js і перекриває його. Те, чого тут
// немає (39 назв класів поза 4.6), лишається англійським.

lang = $.extend(true, lang, {
	base: {
		"sec": "с",
		"min": "хв",
		"hour": "год",
		"novalue": "[немає значення]",
		"reqlvl": "Доступно з %1 рівня",
		"shards": "Потрібно шардів: %1",
		"nodesc": "Опису немає",
		"cost": "Вартість уміння",
		"cooltime": "Відкат",
		"casttime": "Час використання",
		"instant": "Миттєво",
		"stage": "Етап %1"
	},
	other: {
		"everyhit": "атака",
		"stumble": "Збивання з ніг",
		"openaerial": "підкидання в повітря",
		"nmlatk": "атака",
		"phhit": "фізична атака",
		"magical": "магічні атаки",
		"attackrange": "Дальність атаки",
		"bow": "Лук",
		"physical": "Фізична атака",
		"pmdefend": "Фізичний захист і захист від усіх стихій",
		"pmattack": "Фізична й магічна атака"
	},
	classes: {
		"all": "Усі класи",
		"assassin": "Вбивця",
		"ranger": "Стрілець",
		"chanter": "Чародій",
		"priest": "Цілитель",
		"fighter": "Гладіатор",
		"knight": "Охоронець",
		"wizard": "Чарівник",
		"elementalist": "Заклинач",
		"bard": "Бард",
		"gunner": "Стрілець-технік",
		"rider": "Вершник"
	},
	abyssranks: {
		"rank_min": "Мін. ранг Безодні: %1",
		"rank_max": "Макс. ранг Безодні: %1",
		"rank1": "Воїн 9 рангу",
		"rank2": "Воїн 8 рангу",
		"rank3": "Воїн 7 рангу",
		"rank4": "Воїн 6 рангу",
		"rank5": "Воїн 5 рангу",
		"rank6": "Воїн 4 рангу",
		"rank7": "Воїн 3 рангу",
		"rank8": "Воїн 2 рангу",
		"rank9": "Воїн 1 рангу",
		"rank10": "Офіцер 1 зірки",
		"rank11": "Офіцер 2 зірок",
		"rank12": "Офіцер 3 зірок",
		"rank13": "Офіцер 4 зірок",
		"rank14": "Офіцер 5 зірок",
		"rank15": "Генерал",
		"rank16": "Великий генерал",
		"rank17": "Командувач",
		"rank18": "Правитель"
	},
	'skillnames': {
		"as_assaultslash": "Кровоточивий поріз",
		"as_backblow": "Зворотний руйнівний удар",
		"as_blindingburst": "Туманна завіса",
		"as_blindside": "Засідка",
		"as_carvesignetchain": "Нанесення складного клейма",
		"as_chainsignetburst": "Спалах складного клейма",
		"as_defendroar_dark": "Перевтілення: Вбивця",
		"as_defendroar_light": "Перевтілення: Вбивця",
		"as_explosionpoison": "Порох",
		"as_flashslash": "Розсікаюча блискавка",
		"as_hitmanmind": "Клятва точності",
		"as_mirrorattack": "Кидок сюрикена",
		"as_quickmove": "Клятва швидкості",
		"as_runnersstance": "Порятунок",
		"as_senseboost": "Обострення почуттів",
		"as_shadowdodge": "Тіньова ілюзія",
		"as_shadowdrop": "Падіння в тінь",
		"as_signetflare": "Знищення печатки",
		"as_signetwave": "Нанесення клейма на відстані",
		"as_silentburst": "Спалах клейма мовчання",
		"as_stabstance": "Готовність",
		"as_stigma_demonicburst_dark": "[Давня стигма] Запалення клейма темряви",
		"as_stigma_moonburst_dark": "Запалення печатки чорного пекла",
		"as_stigma_novaburst_light": "[Давня стигма] Спалах клейма світла",
		"as_stigma_shadowwalk": "Тіньовий крок",
		"as_stigma_sunburst_light": "Спалах печатки небес",
		"as_stunburst": "Блискуча спалах",
		"as_stuningintention": "Застосування смертельних отрут",
		"as_tigerassault": "Чудовиський шрам",
		"as_venomslash": "Клинок обмороку",
		"as_venomstab": "Атака отрутою",
		"as_visiouseye": "Око гніву",
		"as_whisperofgale": "Клятва ухилення",
		"as_windslash": "Стрімкий розсікаючий удар",
		"ba_delayparalyze": "Ехо паралічу",
		"ba_focusdefence": "Мотив заліза",
		"ba_lullaby": "Танець жартівника",
		"ba_playingstyleschangea": "Закон зцілення",
		"ba_playingstyleschangeb": "Закон посилення",
		"ba_sanctuary": "Акорд сніжинки",
		"ba_songofbind": "Захоплюючий гуркіт",
		"ba_songofbless": "Мотив звільнення",
		"ba_songofbrave": "Мотив відваги",
		"ba_songofearth": "Бджолиний марш",
		"ba_songoffirm": "Мотив самовладання",
		"ba_songofgale": "Акорд дисгармонії",
		"ba_songofmanareverse": "Рапсодія забуття",
		"ba_songofmassheal": "Мелодія зцілення",
		"ba_songofpain": "Рапсодія мушки",
		"ba_songofregeneration": "Мотив народження",
		"ba_songofresurrection": "Небесний реквієм",
		"ba_songofserenity": "Мелодія незворушності",
		"ba_songogpeace": "Ноктюрн світу",
		"ch_blessprotect": "Благословення стійкості",
		"ch_chakra": "Відновлення життєвої сили",
		"ch_chant_improvedcritical": "Закляття удачі",
		"ch_chant_improvedresiststun": "Закляття посилення",
		"ch_chant_invincible": "Закляття невразливості",
		"ch_encouragerun": "Натхнення екстазу",
		"ch_harshthrust": "Смертельний удар",
		"ch_healingtank": "Обряд поглинання",
		"ch_heroicstrike": "Фатальний удар",
		"ch_imbuepower": "Благословення вітру",
		"ch_improvedallattack": "Обряд натхнення",
		"ch_improvedalldefend": "Обряд захисту",
		"ch_improvedbody": "Обряд неприступності",
		"ch_improvedlifestream": "Обряд життя",
		"ch_mountaincrash": "Руйнівний удар",
		"ch_mpheal": "Магічне відновлення",
		"ch_nightwish": "Обряд люті",
		"ch_phoenixstep": "Управління небесами",
		"ch_protectself": "Самозахист",
		"ch_shockwave": "Атакуюча хвиля",
		"ch_slowcrash": "Шоковий удар",
		"ch_soaredrock": "Удар землі",
		"ch_splashswing": "Розлючений замах",
		"ch_stigma_angelicwall_light": "Захисний покров",
		"ch_stigma_angelicwish_light": "[Давня стигма] Обряд перешкоди",
		"ch_stigma_demonicwall_dark": "Ефірний покров",
		"ch_stigma_demonicwish_dark": "[Давня стигма] Обряд межі",
		"ch_stigma_recoverword": "Обряд відновлення",
		"ch_surperiorheal": "Длань відновлення",
		"ch_swordbind": "Кидок оков",
		"ch_thruststrike": "Буйство",
		"ch_triplethrust": "Шквал уколів",
		"cl_imbuemana": "Клятва ефіру",
		"el_bind": "Заточення плоті",
		"el_dimisspolymorph": "Атака елементаля",
		"el_drainenergy": "Поглинання життєвої сили",
		"el_earthguardiance": "Охоронець землі",
		"el_elementalboost": "Зцілення розуму",
		"el_elementalcharge": "Посилення елемента: Відновлення",
		"el_elementtransfer": "Перехід енергії",
		"el_enchantarmor": "Посилення елементаля: Посилені обладунки",
		"el_enchantmentburst": "Магічне загоряння",
		"el_enervationcurse": "Прокляття темряви",
		"el_enfeeblement": "Сповільнюючі кайдани",
		"el_escape": "Герб маскування",
		"el_ethercharge": "Посилення елементаля: Відновлення",
		"el_fireaid": "Благословення вогню",
		"el_hellcurse": "Загробне прокляття",
		"el_hellpain": "Невитримувані муки",
		"el_manareverse": "Спалити чари",
		"el_order_elementalfield": "Команда: Стіна захисту",
		"el_order_omen": "Команда: Гіпноз",
		"el_order_protect": "Команда: Захист",
		"el_order_sacrifice": "Команда: Заміна",
		"el_silence": "Блокування магії",
		"el_slave_stormservent_dark": "Заклик: Енергія урагану",
		"el_slave_stormservent_light": "Заклик: Енергія урагану",
		"el_sleepingspirit": "Узи сну",
		"el_soulsteal": "Крадіжка душі",
		"el_stigma_order_destructimpact": "Команда: Руйнівна атака",
		"el_stigma_order_etheremission_light": "[Давня стигма] Команда: Жертва",
		"el_stigma_order_ethereruption_light": "Команда: Спалити дотла",
		"el_stigma_order_etherimpact_dark": "[Давня стигма] Команда: Самознищення",
		"el_stigma_order_shadoweruption_dark": "Команда: Спалах",
		"el_stigma_stormblade": "Ураган гніву",
		"el_sympatheticswitch": "Жертва елементаля",
		"el_terrorspirit": "Вопль жаху",
		"fi_anklegrab": "Захоплення ніг",
		"fi_anklesnatcher": "Зв'язування ніг",
		"fi_berserkstance": "Стійка берсерка",
		"fi_blademode": "Підготовка до бою",
		"fi_burserklance": "Затоптування",
		"fi_charginghit": "Руйнівний удар",
		"fi_chargingshock": "Знищувальний удар",
		"fi_cripplingcut": "Нисхідний удар",
		"fi_drainsword": "Меч вампіра",
		"fi_enfeeblehit": "Виснажливий удар",
		"fi_heavyimpact": "Хвиля землетрусу",
		"fi_howling": "Загрозливий рев",
		"fi_jumpattack": "Удар з повітря",
		"fi_kneecrash": "Різка ніг",
		"fi_lockdownimpact": "Ізоляція",
		"fi_magicalbarrier": "Захист маг.енергією",
		"fi_potentialhealth": "Оздоровлення",
		"fi_ragespirit": "Безстрашність",
		"fi_revengeslash": "Удар помсти",
		"fi_seismicdrain": "Вампірська хвиля",
		"fi_sharpnesshit": "Колючий удар",
		"fi_spinningparry": "Концентрація на розвороті",
		"fi_stigma_draincut": "Випити крові",
		"fi_stigma_forceblast_light": "[Давня стигма] Ударна міць меча",
		"fi_stigma_forceburst_light": "Бійня",
		"fi_stigma_shockburst_dark": "Різанина",
		"fi_stigma_shockimpulse_dark": "[Давня стигма] Хвиля бойового безумства",
		"fi_survivorstance": "Друге дихання",
		"fi_technicalcounter": "Майстер контратаки",
		"fi_vorpalhit": "Рубаючий удар",
		"fi_whirldrain": "Виснажуюча хвиля",
		"fi_whirltornado": "Відновлювальна хвиля",
		"gu_antigravitycannon": "Сковуюче ядро",
		"gu_armorbreak": "Ядро розлому",
		"gu_bullseye": "Сфокусованість",
		"gu_empowerammo": "Посилення магічного вибуху",
		"gu_empowermagic": "Мудрість магії",
		"gu_firechainrefresh": "Зарядка магічного вибуху",
		"gu_flamecannon": "Вогняний залп",
		"gu_icecannon": "Удар замороження",
		"gu_magicalbreathing": "Магічне дихання",
		"gu_mentaliccannon": "Розсікаюча гармата",
		"gu_mentalsnatcher": "Поглинаючий постріл",
		"gu_onepointrapidfire": "Швидкий постріл",
		"gu_rapidstance": "Прискорення стрільби",
		"gu_shockcannon": "Шокова гармата",
		"gu_silenceshot": "Заряд німоти",
		"gu_soulbreakcannon": "Примарна гармата",
		"gu_sunningshot": "Приголомшливий постріл",
		"gu_survivalinstinct": "Інстинкт життя",
		"gu_vassblaster": "Виклик канонади",
		"gu_veinsnipe": "Проникаючий постріл",
		"kn_absolutescare": "Крик жаху",
		"kn_brainstorm": "Руйнування свідомості",
		"kn_breakpower": "Підсічка",
		"kn_conquestmind": "Здатність відновлення",
		"kn_destructshield": "Щит руйнування",
		"kn_destructwish": "Жага руйнування",
		"kn_divinepower": "Збурення",
		"kn_divineslash": "Покарання",
		"kn_executionalstrike": "Усувальний удар",
		"kn_fortitudewave": "Хвиля оков",
		"kn_grandprotection": "Захист союзників",
		"kn_highprovoke": "Виклик гніву",
		"kn_holywrath": "Охоронний щит",
		"kn_intimidation": "Загроза",
		"kn_invinsibleprotect": "Захист богів",
		"kn_invinsibleshield": "Міцний щит",
		"kn_massiveprovoke": "Знущальний регіт",
		"kn_movingstance": "Нижня захист",
		"kn_powersink": "Руйнівний магічний удар",
		"kn_recover": "Реанімація",
		"kn_reflectshield": "Відбивна захист",
		"kn_revivaltouch": "Відновлювальна долоня",
		"kn_sentinel": "Броня покровительства",
		"kn_stigma_demonpunishment_dark": "Правосуддя темряви",
		"kn_stigma_drainsword_dark": "[Давня стигма] Правосуддя бога смерті",
		"kn_stigma_godjudgement_light": "[Давня стигма] Правосуддя богів",
		"kn_stigma_godpunishment_light": "Правосуддя світла",
		"kn_stigma_resistarmor": "Захисний блок",
		"kn_stunningsnacher": "Перехоплення",
		"kn_thunderblade": "Розкат грому",
		"kn_triplesnacher": "Ілюзорний захват",
		"p_equip_dual": "Парна зброя: практика",
		"pr_bindingheal": "Цілюще співчуття",
		"pr_blindinglight": "Блік",
		"pr_calllightning": "Розкати грому",
		"pr_coursewound": "Заборона відновлення",
		"pr_eternalservent_dark": "Заклик: Свята енергія",
		"pr_eternalservent_light": "Заклик: Свята енергія",
		"pr_firstaid": "Мерехтіння відновлення",
		"pr_graceofgod": "Благословення богів",
		"pr_healershand": "Право на життя",
		"pr_healinggrace": "Покровительство цілителя",
		"pr_healingservent_dark": "Заклик: Енергія зцілення",
		"pr_healingservent_light": "Заклик: Енергія зцілення",
		"pr_massdispel": "Сяйво очищення",
		"pr_massemergentheal": "Сяйво відновлення",
		"pr_memoryblur": "Розсіювання пам'яті",
		"pr_offensivemode": "Право на знищення",
		"pr_painlinks": "Цепка страждань",
		"pr_powersmite": "Правосуддя землі",
		"pr_purgatory": "Натиск землі",
		"pr_regeneraitionshine": "Сяйво регенерації",
		"pr_restorelife": "Рятівна долоня",
		"pr_reversecondition": "Реверс",
		"pr_revivehand": "Відроджуюча долоня",
		"pr_sageswisdom": "Молитва швидкості",
		"pr_sprint": "Різке прискорення",
		"pr_stigma_abysalcircle_dark": "[Давня стигма] Світ Маркутана",
		"pr_stigma_abysalsanctuary_dark": "Сяйво Маркутана",
		"pr_stigma_divinecircle_light": "[Давня стигма] Світло Юстіїля",
		"pr_stigma_divinesanctuary_light": "Сяйво Юстія",
		"pr_stigma_suggestion": "Стійкість",
		"pr_suffermemory": "Ослаблююче клеймо",
		"pr_thunderofpunishment": "Блискавка помсти",
		"pr_tranquility": "Хвиля святості",
		"ra_backdashstab": "Відступ",
		"ra_blazingtrap_dark": "Несамовита пастка",
		"ra_blazingtrap_light": "Несамовита пастка",
		"ra_breathofnature": "Дихання матері-природи",
		"ra_callcompanion_dark": "Заклик симурга",
		"ra_callcompanion_light": "Заклик симурга",
		"ra_draineye": "Поглинання магії",
		"ra_enchantbow": "Благословенна стріла",
		"ra_explosionarrow": "Розривна стріла",
		"ra_fairyflare_dark": "Пастка ясновидіння",
		"ra_fairyflare_light": "Пастка ясновидіння",
		"ra_heavenstrap_dark": "Обплітаюча пастка",
		"ra_heavenstrap_light": "Обплітаюча пастка",
		"ra_huntermind": "Уловка мисливця",
		"ra_instantsprint": "Миттєвий крок",
		"ra_lightningshot": "Блискавична стріла",
		"ra_marksmanmode": "Приготування до стрільби",
		"ra_massexplosionarrow": "Стріла ярості",
		"ra_movingshot": "Стріла вітру",
		"ra_painarrow": "Стріла страждань",
		"ra_panthermove": "Божевільний вітер",
		"ra_paralyzearrow": "Усипляюча стріла",
		"ra_rapidshot": "Вопляча стріла",
		"ra_resistmind": "Рішучий опір",
		"ra_sealingarrow": "Зв'язуючий постріл",
		"ra_shadowarrow": "Стріла лютого вітру",
		"ra_silentarrow": "Стріла мовчання",
		"ra_snakebitetrap_dark": "Пастка злого духа",
		"ra_snakebitetrap_light": "Пастка злого духа",
		"ra_spoutarrow": "Злива стріл",
		"ra_stigma_ancientarrow_light": "Стріла Грифонії",
		"ra_stigma_destructarrow_dark": "[Давня стигма] Стріла кондора",
		"ra_stigma_mysticarrow_dark": "Стріла Консіода",
		"ra_stigma_phoenixarrow_light": "[Давня стигма] Стріла грифона",
		"ra_stigma_tigereye": "Тигриний око",
		"ra_throwingtrap_dark": "Сповільнююча пастка",
		"ra_throwingtrap_light": "Сповільнююча пастка",
		"ra_trackermind": "Посилення стріл",
		"ri_bindingslam": "Електричні окови",
		"ri_chainfire": "Неперервний вогонь",
		"ri_eathiumblast": "Ідіумова канонада",
		"ri_eathiumcompress": "Магічна компресія",
		"ri_eathiumcurtain": "Захисне поле",
		"ri_eathiumreactive": "Магічна перезарядка",
		"ri_eathiumwall": "Бар'єр іда",
		"ri_flamethrow": "Ідіумове покарання",
		"ri_forwardstrike": "Сокрушуюча хвиля",
		"ri_itheumreflector": "Амортизуюча мембрана",
		"ri_magneticfield": "Енергетичний бар'єр",
		"ri_overcharge": "Максимальна віддача",
		"ri_poweroverdrive": "Підвищення бойової спроможності",
		"ri_powerslam": "Руйнівний прорив",
		"ri_rapidattack": "Град атак",
		"ri_rapidcharge": "Швидка перезарядка",
		"ri_shielddestroyer": "Знищення бар'єрів",
		"ri_speedoverdrive": "Підвищення рухливості",
		"ri_tunesensor": "Регулювання",
		"ri_weaponsmash": "Виснажливий удар",
		"sc_trueshotmind": "Лютий погляд",
		"wa_gatecrush": "Знищення воріт",
		"wa_steadiness": "Броня балансу",
		"wi_arcaneboost": "Мудрість Байзела",
		"wi_arcanepower": "Мудрість Джикела",
		"wi_arcanewisdom": "Мудрість Руміеля",
		"wi_countermagic": "Прокляття слабкості",
		"wi_cursedtree": "Прокляття: Дерево",
		"wi_cyclonestrike": "Штормовий удар",
		"wi_deepsleep": "Спрямований сон",
		"wi_elementalseal": "Стихійний бар'єр",
		"wi_flamestrike": "Ярість вогню",
		"wi_frostpillar_dark": "Льодовий стовп",
		"wi_frostpillar_light": "Льодовий стовп",
		"wi_hibernation": "Льодяні окови",
		"wi_hpmpexchange": "Обмін життєвою силою",
		"wi_icebarrier": "Бар'єр розділення",
		"wi_icyshield": "Крижані обладунки",
		"wi_icyveins_dark": "Дар швидкості",
		"wi_icyveins_light": "Дар посилення",
		"wi_illusiondance": "Ілюзія",
		"wi_illusionstorm": "Ураган ілюзій",
		"wi_massexplosion": "Вогняна спалах",
		"wi_rockfall": "Заклик скелі",
		"wi_sleepingstorm": "Шторм сну",
		"wi_soulgain": "Мольба концентрації",
		"wi_stigma_atomicenergy_dark": "[Давня стигма] Лавове цунамі",
		"wi_stigma_atomicenergy_light": "[Давня стигма] Вулканічний спалах",
		"wi_stigma_icelance": "Льодовий гарпун",
		"wi_stigma_lavawave_dark": "Лавовий тайфун",
		"wi_stigma_volcanicflame_light": "Потужний вулканічний спалах",
		"wi_stormshock": "Падіння блискавки",
		"wi_summontornado_dark": "Торнадо",
		"wi_summontornado_light": "Торнадо",
		"wi_wakeup": "Скасування сну",
		"wi_windcutter": "Лезо вітру",
		"wi_zeropoint": "Льодовий удар"
	},
	skilldesc: {
		"as_assaultslash": "Здійснює ривок до супротивника в радіусі [%First_Target_Valid_Distance] м і завдає йому [%e1.DashATK.MinDamage]-[%e1.DashATK.MaxDamage] од. шкоди. Потрібна стигма.",
		"as_backblow": "Фізична атака, завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди під час маскування. Миттєво оглушує ціль. Потрібна стигма.",
		"as_blindingburst": "Сліпить ворогів в радіусі 15 м. [%e2.StatDown.StatName] -[%e2.StatDown.Value]. Час дії: [%e1.Blind.RandomTime]-[%e1.Blind.RemainTime] Потрібна стигма.",
		"as_blindside": "Переміщує за спину цілі. Радіус дії: [%First_Target_Valid_Distance] м. Фізична атака, завдає [%e1.MoveBehindATK.MinDamage]-[%e1.MoveBehindATK.MaxDamage] одиниць шкоди. Є ймовірність оглушити ціль. Потрібна стигма.",
		"as_carvesignetchain": "Фізична атака, завдає [%e1.CarveSignet.MinDamage]-[%e1.CarveSignet.MaxDamage] одиниць шкоди. Ставить на ціль клеймо до [%e1.CarveSignet.SignetGrade]-го рівня. 2-ге вміння в серії Нанесення клейма - Нанесення складного клейма Потрібна стигма.",
		"as_chainsignetburst": "Атака магією вогню, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. 2-е вміння в серії Масова спалах клейма - Спалах складного клейма Потрібна стигма.",
		"as_defendroar_dark": "Перетворює на вбивцю на [%e1.ShapeChange.RemainTime] В стані перевтілення [%e2.StatUp.StatName] +[%e2.StatUp.Value], [%e2.StatUp.StatName2] +[%e2.StatUp.Value2], [%e2.StatUp.StatName3] +[%e2.StatUp.Value3]. MP відновлюються швидше. Потрібна стигма.",
		"as_defendroar_light": "Перетворює на вбивцю на [%e1.ShapeChange.RemainTime] В стані перевтілення [%e2.StatUp.StatName] +[%e2.StatUp.Value], [%e2.StatUp.StatName2] +[%e2.StatUp.Value2], [%e2.StatUp.StatName3] +[%e2.StatUp.Value3]. MP відновлюються швидше. Потрібна стигма.",
		"as_explosionpoison": "Покриває зброю отрутою. Потрібна отрута скорпіона (5 шт.). При кожній атаці завдає цілі додатково [%e1.Provoker.OtherSkill.e1.ProcATK_Instant.Damage] од. шкоди з ймовірністю [%e1.Provoker.ConditionProb]%%. Час дії: [%e1.Provoker.RemainTime] Потрібна стигма.",
		"as_flashslash": "Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. [%e2.StatDown.StatName] цілі -[%e2.StatDown.Value]. Час дії: [%e2.StatDown.RemainTime] 2-е вміння в серії Швидкий удар - Розсікаюча блискавка Потрібна стигма.",
		"as_hitmanmind": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. Час дії: [%e1.StatUp.RemainTime]",
		"as_mirrorattack": "Фізична атака, завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] одиниць шкоди цілі в повітряних оковах. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"as_quickmove": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%%. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"as_runnersstance": "Скасовує всі накладені на персонажа негативні ефекти пересування. На 7 сек. збільшує опір до оглушення, відштовхування, перекидання, розвороту та повітряним оковам на 500. Потрібна стигма.",
		"as_senseboost": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. [%e2.StatUp.StatName2] +[%e2.StatUp.Value2]. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"as_shadowdodge": "Дозволяє миттєво переміститися вперед на [%e1.RandomMoveLoc.Distance] м. Знімає ефекти знерухомлення і сповільнення. Потрібна стигма.",
		"as_shadowdrop": "Фізична атака, перекидає оглушену ціль і завдає їй [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Потрібна стигма.",
		"as_signetflare": "Активує печатку, що завдає шкоду цілі в радіусі [%First_Target_Valid_Distance] м. Печатка активується до [%e1.SignetBurst.SignetGrade]-го рівня. Завдана шкода залежить від рівня печатки цілі. Потрібна стигма.",
		"as_signetwave": "Фізична атака, завдає [%e1.CarveSignet.MinDamage]-[%e1.CarveSignet.MaxDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. Ставить на ціль клеймо до [%e1.CarveSignet.SignetGrade]-го рівня. Потрібна стигма.",
		"as_silentburst": "Активує клеймо до [%e1.SignetBurst.SignetGrade]-го рівня, яке завдає цілі шкоди і накладає на неї німоту на 30 с. Радіус дії: [%First_Target_Valid_Distance] м. Шанс виклику німоти залежить від рівня клейма цілі. Потрібна стигма.",
		"as_stabstance": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%%. [%e2.StatDown.StatName] -[%e2.StatDown.Value]. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"as_stigma_demonicburst_dark": "Стигма давнього даєва. Активує на цілі клеймо до [%e1.SignetBurst.SignetGrade]-го рівня, вороги в радіусі [%First_Target_Valid_Distance] м отримують шкоду від вибуху, частина якої йде на відновлення HP персонажа. Потрібна стигма.",
		"as_stigma_moonburst_dark": "Активує на цілі печатку до [%e1.SignetBurst.SignetGrade]-го рівня, вороги в радіусі [%First_Target_Valid_Distance] м отримують шкоду від вибуху, частина якої йде на відновлення HP персонажа. Потрібна стигма.",
		"as_stigma_novaburst_light": "Стигма давнього даєва. Активує клеймо до [%e1.SignetBurst.SignetGrade]-го рівня, яке завдає цілі шкоду вибухом, на час знижує швидкість атаки та накладає німоту. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"as_stigma_shadowwalk": "Ви в стані покращеного маскування. Час дії: [%e1.Hide.RemainTime] Швидкість руху в стані маскування: [%e1.Hide.Speed]%%. При маскуванні можна застосовувати посилюючу магію не більше 3 разів. Неможливо використовувати під час бою. Потрібна стигма.",
		"as_stigma_sunburst_light": "Активує печатку до [%e1.SignetBurst.SignetGrade]-го рівня, яка завдає цілі шкоду вибухом, на час знижує швидкість атаки та накладає німість. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"as_stunburst": "Магічна атака вогнем, завдає цілі [%e1.SpellATK_Instant.FixDamage] од. шкоди та оглушує її. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"as_stunburst_2": "Магічна атака вогнем, завдає цілі [%e1.SpellATK_Instant.FixDamage] од. шкоди та оглушує її. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"as_stuningintention": "Покриває зброю отрутою. Потрібна отрута скорпіона (2 шт.). При кожній атаці протягом [%e1.Provoker.RemainTime] є ймовірність [%e1.Provoker.ConditionProb]%% оглушити супротивника. Потрібна стигма.",
		"as_tigerassault": "Фізична атака, завдає [%e1.CarveSignet.MinDamage]-[%e1.CarveSignet.MaxDamage] од. шкоди. Накладає на ціль печатку до [%e1.CarveSignet.SignetGrade]-го рівня. 4-е вміння в серії Кидок звіра - Чудовиський шрам Потрібна стигма.",
		"as_venomslash": "Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Якщо ціль отруєна, додатково завдає [%e1.SkillATK_Instant.AddDamage] од. шкоди та на короткий час оглушає її. Потрібна стигма.",
		"as_venomstab": "Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. При нападі ззаду завдає додатково [%e1.SkillATK_Instant.AddDamage] од. фізичної шкоди і отруює ціль на [%e2.Poison.RemainTime] Потрібна стигма.",
		"as_visiouseye": "Після використання вміння атакує критичним ударом. Кількість атак: [%e1.OneTimeBoostSkillCritical.BoostCount]. Час дії: [%e1.OneTimeBoostSkillCritical.RemainTime] [%e2.StatDown.StatName] -[%e2.StatDown.Value]. Потрібна стигма.",
		"as_whisperofgale": "Дозволяє відбивати магічні атаки. Кількість відбиттів: [%e1.AlwaysResist.Count]. Час дії: [%e1.AlwaysResist.RemainTime] Потрібна стигма.",
		"as_windslash": "Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. [%e2.StatDown.StatName] -[%e2.StatDown.Value]. [%e3.StatDown.StatName] -[%e3.StatDown.Value]. Час дії: [%e2.StatDown.RemainTime] 2-е вміння в серії Стрімкий удар - Стрімкий розсікаючий удар Потрібна стигма.",
		"ba_delayparalyze": "Через 8 сек. після активації вміння паралізує ціль у радіусі [%First_Target_Valid_Distance] м на 5 сек. Потрібна стигма.",
		"ba_focusdefence": "[%e1.StatUp.StatName]% +[%e1.StatUp.Value]. Час дії: [%e1.StatUp.RemainTime] Зменшує шкоду від атак інших персонажів. Потрібна стигма.",
		"ba_lullaby": "Усипляє ціль. [%e3.StatUp.StatName] +[%e3.StatUp.StatName2]. Час дії: [%e2.Sleep.RemainTime] Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ba_playingstyleschangea": "[%e1.StatBoost.StatName]% +[%e1.StatBoost.fixValue]%. Потрібна стигма.",
		"ba_playingstyleschangeb": "[%e1.StatBoost.StatName] +[%e1.StatBoost.fixValue]. [%e2.StatBoost.StatName] +[%e2.StatBoost.fixValue]. Потрібна стигма.",
		"ba_sanctuary": "Створює захисний барʼєр, який зі 100%% ймовірністю блокує 3000 од. шкоди протягом 30 сек. під час атаки. Відновлює [%e2.Heal_Instant.Heal] HP і [%e3.MPHeal.CheckTimeHeal] MP кожні [%e3.MPHeal.CheckTime].&#xD;",
		"ba_songofbind": "Забороняє цілі використовувати фізичні вміння протягом 5 сек. Потрібна стигма.",
		"ba_songofbless": "Знімає злі чари, що діють на персонажа та членів його групи в радіусі 25 м, і відновлює по [%e2.Heal.CheckTimeHeal] HP з інтервалом у [%e2.Heal.CheckTime] Час дії: [%e2.Heal.RemainTime] Потрібна стигма.",
		"ba_songofbrave": "[%e1.StatUp.StatName]% +[%e1.StatUp.Value]%. [%e1.StatUp.StatName2] і [%e1.StatUp.StatName3]% +[%e1.StatUp.Value2]%. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"ba_songofearth": "Удар магією землі, завдає цілі в радіусі [%First_Target_Valid_Distance] м [%e1.SpellATK_Instant.FixDamage] од. шкоди. При цьому її [%e2.StatDown.StatName] -[%e2.StatDown.Value]. Час дії: [%e2.StatDown.RemainTime] Потрібна стигма.",
		"ba_songoffirm": "[%e1.StatUp.StatName]% і [%e1.StatUp.StatName3]% +[%e1.StatUp.Value]%. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"ba_songofgale": "Удар магією повітря, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ba_songofmanareverse": "Скасовує 2 магічні посилення цілі. Потрібна стигма.",
		"ba_songofmassheal": "Відновлює [%e1.Heal_Instant.Heal] HP цілі в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ba_songofmassheal_2": "Відновлює [%e1.Heal_Instant.Heal] HP цілі в радіусі [%First_Target_Valid_Distance] м.",
		"ba_songofmassheal_3": "Відновлює [%e1.Heal_Instant.Heal] HP цілі в радіусі [%First_Target_Valid_Distance] м.",
		"ba_songofpain": "Завдає додатково [%e1.SpellATK.Damage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м раз на [%e1.SpellATK.CheckTime] Час дії: [%e1.SpellATK.RemainTime] Через [%e2.SpellATK.RemainTime] завдає додатково [%e2.SpellATK.Damage] од. шкоди. Потрібна стигма.",
		"ba_songofregeneration": "Відновлює по [%e1.Heal.CheckTimeHeal] HP цілі з інтервалом у [%e1.Heal.CheckTime] Час дії: [%e1.Heal.RemainTime] Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ba_songofresurrection": "Відроджує ціль в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ba_songofserenity": "Відновлює [%e1.MpHeal_Instant.Heal] МP цілі в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ba_songofserenity_2": "Відновлює [%e1.MpHeal_Instant.Heal] МП персонажа або цілі в радіусі [%First_Target_Valid_Distance] м.",
		"ba_songofserenity_3": "Відновлює [%e1.MpHeal_Instant.Heal] МП цілі в радіусі [%First_Target_Valid_Distance] м від персонажа та 6 союзникам на відстані 10 м від неї.",
		"ba_songogpeace": "Зменшує ворожість цілі. Потрібна стигма.",
		"ch_blessprotect": "[%e1.StatUp.StatName] цілі +[%e1.StatUp.Value]%%. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. [%e3.StatUp.StatName] +[%e3.StatUp.Value]%%. [%e1.StatUp.StatName2]% +[%e1.StatUp.Value2]. Радіус дії: [%First_Target_Valid_Distance] м. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"ch_chakra": "Відновлює [%e1.Heal_Instant.Heal] HP і [%e2.MPHeal_Instant.Heal] MP. Потрібна стигма.",
		"ch_chant_improvedcritical": "Збільшує параметри персонажа та членів його групи: [%e1.Aura.OtherSkill.e1.StatUp.StatName]%+[%e1.Aura.OtherSkill.e1.StatUp.Value], [%e1.Aura.OtherSkill.e1.StatUp.StatName2]% +[%e1.Aura.OtherSkill.e1.StatUp.Value2], [%e1.Aura.OtherSkill.e2.StatUp.StatName]% +[%e1.Aura.OtherSkill.e2.StatUp.Value], [%e1.Aura.OtherSkill.e2.StatUp.StatName2]% +[%e1.Aura.OtherSkill.e2.StatUp.Value2]. Радіус дії: [%e1.Aura.Range] м. Активне вміння. Потрібна стигма.",
		"ch_chant_improvedresiststun": "[%e1.Aura.OtherSkill.e1.StatUp.StatName] +[%e1.Aura.OtherSkill.e1.StatUp.Value]. Діє на персонажа та членів його групи, що знаходяться в радіусі [%e1.Aura.Range] м. Активне вміння",
		"ch_chant_invincible": "Відновлює [%e1.Aura.OtherSkill.e1.MPHeal.CheckTimeHeal] MP персонажа і членів групи в радіусі [%e1.Aura.Range] м. [%e1.Aura.OtherSkill.e2.StatUp.StatName], [%e1.Aura.OtherSkill.e3.StatUp.StatName] і [%e1.Aura.OtherSkill.e4.StatUp.StatName] збільшуються. Активне вміння Потрібна стигма.",
		"ch_encouragerun": "[%e1.StatUp.StatName] союзника в радіусі [%First_Target_Valid_Distance] м збільшується на [%e1.StatUp.Value]%%. Час дії: 7 сек. Витрачає HP. Потрібна стигма.",
		"ch_harshthrust": "Сильна фізична атака, що вимагає підготовки. Завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Потрібна стигма.",
		"ch_harshthrust_2": "Сильна фізична атака, що вимагає підготовки. Завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Потрібна стигма.",
		"ch_harshthrust_3": "Сильна фізична атака, що вимагає підготовки. Завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Потрібна стигма.",
		"ch_healingtank": "Відновлює [%e1.HealCastorOnAttacked.HealPoint] HP персонажа та членів його групи при кожному завданні шкоди. Час дії: [%e1.HealCastorOnAttacked.RemainTime] Радіус дії: [%e1.HealCastorOnAttacked.EffectArea] м. Потрібна стигма.",
		"ch_heroicstrike": "Фізична атака, завдає оглушеному ворогу [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди та вводить його в стан [%e1.SkillATK_Instant.AddEffect]. Потрібна стигма.",
		"ch_imbuepower": "Завдає цілі додатково [%e1.Provoker.OtherSkill.e1.ProcATK_Instant.Damage] од. шкоди з ймовірністю [%e1.Provoker.ConditionProb]%%. Необхідна умова: [%e1.Provoker.Condition]. Час дії: [%e1.Provoker.RemainTime] Потрібна стигма.",
		"ch_improvedallattack": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. [%e3.StatUp.StatName] +[%e3.StatUp.Value]%%. Діє на членів групи в радіусі 20 м. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"ch_improvedalldefend": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. Діє на всіх членів групи в радіусі 20 м. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"ch_improvedbody": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. Діє на вашого персонажа та 6 членів альянсу в 20 м від нього. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"ch_improvedlifestream": "Відновлює по [%e1.Heal.CheckTimeHeal] HP вашого персонажа та членів його групи, що знаходяться в радіусі 20 м, з інтервалом у [%e1.Heal.CheckTime] Час дії: [%e1.Heal.RemainTime] Потрібна стигма.",
		"ch_mountaincrash": "Завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Радіус дії: [%First_Target_Valid_Distance] м. Завдає додатково [%e2.SpellATK.Damage] од. шкоди з інтервалом в [%e2.SpellATK.CheckTime] Час дії: [%e2.SpellATK.RemainTime] Потрібна стигма.",
		"ch_mpheal": "Відновлює [%e1.MPHeal_Instant.Heal] MP персонажа або цілі в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ch_nightwish": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%%. Час дії: [%e1.StatUp.RemainTime] Час підготовки лікувальних вмінь збільшується на 20%%. Потрібна стигма.",
		"ch_phoenixstep": "Знімає стани оглушення, відштовхування, перекидання, розвороту і повітряних оков. [%e2.StatUp.StatName] +[%e2.StatUp.Value] на [%e2.StatUp.RemainTime] 1-е вміння в серії Потрібна стигма.",
		"ch_protectself": "Захисний бар'єр, з ймовірністю [%e1.Shield.ConditionProb]%% поглинає шкоду. Необхідна умова: [%e1.Shield.Condition] на персонажа. Поки бар'єр діє, опір перекиданню збільшується. Час дії: [%e1.Shield.RemainTime] (Поглинає при кожному ударі [%e1.Shield.CoverValue]%% шкоди.) Потрібна стигма.",
		"ch_shockwave": "Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди та приводить її в стан [%e1.SkillATK_Instant.AddEffect]. Потрібна стигма",
		"ch_slowcrash": "Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Зменшує швидкість атаки. Також знижує швидкість магії на 50%%. Час дії: [%e2.Slow.RemainTime] Потрібна стигма.",
		"ch_soaredrock": "Завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди оглушеному або збитому з ніг супротивнику в радіусі [%First_Target_Valid_Distance] м і блокує його фізичні вміння на [%e2.bind.RemainTime] Потрібна стигма.",
		"ch_splashswing": "Після успішного парирування завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. фізичної шкоди. Потрібна стигма.",
		"ch_stigma_angelicwall_light": "Створює захисний бар'єр, що відновлює по [%e2.Heal.CheckTimeHeal] HP з інтервалом в [%e2.Heal.CheckTime] З ймовірністю [%e1.Shield.ConditionProb]%% запобігає [%e1.Shield.CoverValue]%% шкоди, що завдається персонажу та максимум 6 союзникам в радіусі 20 м від нього. Умова: [%e1.Shield.Condition] на персонажа. Захисний бар'єр зберігається до отримання [%e1.Shield.ShieldValue] од. шкоди. Час дії: [%e1.Shield.RemainTime] Потрібна стигма.",
		"ch_stigma_angelicwish_light": "Стигма давнього даєва. Створює захисний бар'єр, що відновлює по [%e2.Heal.CheckTimeHeal] HP з інтервалом у [%e2.Heal.CheckTime] З ймовірністю [%e1.Shield.ConditionProb]%% запобігає [%e1.Shield.CoverValue]%% шкоди, що завдається персонажу та його союзникам в радіусі 20 м від нього. Умова: [%e1.Shield.Condition] на персонажа. Захисний бар'єр зберігається до отримання [%e1.Shield.ShieldValue] од. шкоди. Час дії: [%e1.Shield.RemainTime] Потрібна стигма.",
		"ch_stigma_demonicwall_dark": "Створює захисний бар'єр, який щоразу, коли на персонажа проводиться [%e1.Shield.Condition], з ймовірністю [%e1.Shield.ConditionProb]%% поглинає шкоду, що отримується персонажем та його союзниками в радіусі 20 м від нього. Захисний бар'єр зберігається щоразу при отриманні [%e1.Shield.CoverValue]%% шкоди, максимум до [%e1.Shield.ShieldValue]. Час дії: [%e1.Shield.RemainTime] Потрібна стигма.",
		"ch_stigma_demonicwish_dark": "Стигма давнього даєва. Створює захисний бар'єр, який кожного разу при отриманні [%e1.Shield.Condition] з ймовірністю [%e1.Shield.ConditionProb]%% поглинає шкоду, що отримується персонажем і союзниками в радіусі 20 м від нього. Захисний бар'єр зберігається кожного разу при отриманні [%e1.Shield.CoverValue]%% шкоди, максимум до [%e1.Shield.ShieldValue]. Час дії: [%e1.Shield.RemainTime] Потрібна стигма.",
		"ch_stigma_recoverword": "Відновлює [%e1.Heal_Instant.Heal] HP цілі в радіусі [%First_Target_Valid_Distance] м, а також додатково відновлює [%e2.Heal.CheckTimeHeal] HP з інтервалом в [%e2.Heal.CheckTime] Час дії: [%e2.Heal.RemainTime] Потрібна стигма.",
		"ch_surperiorheal": "Відновлює [%e1.Heal_Instant.Heal] HP цілі в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ch_swordbind": "Забороняє цілям в радіусі [%First_Target_Valid_Distance] м використовувати фізичні вміння та знижує їхню швидкість руху. Час дії: [%e1.Bind.RemainTime] Потрібна стигма.",
		"ch_thruststrike": "Фізична атака, завдає цілям [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди та оглушає її. 2-е вміння в серії Шквал уколів (х3) - Буйство Потрібна стигма.",
		"ch_triplethrust": "Завдає цілям [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. фізичної шкоди. 3 повтори 1-е вміння в серії Потрібна стигма.",
		"cl_imbuemana": "При кожній атаці протягом [%e1.Provoker.RemainTime] є ймовірність [%e1.Provoker.ConditionProb]%% відновити MP персонажа. Потрібна стигма.",
		"el_bind": "Забороняє цілям використовувати фізичні вміння. Радіус дії: [%First_Target_Valid_Distance] м. Час дії: [%e1.Bind.RandomTime]-[%e1.Bind.RemainTime] Потрібна стигма.",
		"el_dimisspolymorph": "Атака магією повітря, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди в радіусі [%First_Target_Valid_Distance] м. Завдає [%e1.SpellATK_Instant.AddDamage] од. додаткової шкоди, якщо метою є елементаль. Потрібна стигма.",
		"el_drainenergy": "Удар магією вогню, завдає [%e1.SpellATKDrain_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. Перетворює [%e1.SpellATKDrain_Instant.HPHeal]%% завданої шкоди в HP. Потрібна стигма.",
		"el_earthguardiance": "Знімає з вашого персонажа всі негативні ефекти, пов'язані з пересуванням, і підвищує захист від них на 800. Час дії: 10 сек. Потрібна стигма.",
		"el_elementalboost": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]. [%e1.StatUp.StatName3] +[%e1.StatUp.Value3]. Діє на закликувача та елемента. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"el_elementalcharge": "В радіусі [%First_Target_Valid_Distance] м відновлює [%e1.Heal_Instant.Heal]%% HP елемента та знімає всі накладені на нього злі чари. Потрібна стигма.",
		"el_elementtransfer": "Відновлює [%e1.MPHeal_Instant.Heal] МР союзнику, що знаходиться в радіусі 25 м, за рахунок 10%% власних НР. Потрібна стигма.",
		"el_enchantarmor": "Змінює наступні параметри елементаля: [%e1.StatUp.StatName] +[%e1.StatUp.Value]%%, [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]%%, [%e1.StatUp.StatName3] +[%e1.StatUp.Value3], [%e2.StatUp.StatName] +[%e2.StatUp.Value]%%, [%e2.StatUp.StatName2] +[%e2.StatUp.Value2], [%e2.StatUp.StatName3] +[%e2.StatUp.Value3]. Радіус дії: [%First_Target_Valid_Distance] м. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"el_enchantmentburst": "Скасовує посилюючу магію на цілі (максимум до [%e1.DispelBuffCounterATK.DispelCount] шт.). При скасуванні одного ефекту завдає [%e1.DispelBuffCounterATK.Damage] од. шкоди. У разі скасування більше одного ефекту завдає по [%e1.DispelBuffCounterATK.AddDamage] од. додаткової шкоди. 1-е вміння в серії Потрібна стигма.",
		"el_enervationcurse": "Зменшує на [%e1.Curse.Value] максимальну кількість HP та MP цілі. Час дії: [%e1.Curse.RemainTime] Радіус дії: [%First_Target_Valid_Distance] м. Можна зняти за допомогою вміння \"Зняття злих чар\". Потрібна стигма.",
		"el_enfeeblement": "Зменшує швидкість атаки та збільшує час підготовки магічних вмінь цілі в радіусі [%First_Target_Valid_Distance] м. При цьому [%e2.StatDown.StatName] -[%e2.StatDown.Value]. Час дії: [%e1.Slow.RemainTime] Можна видалити за допомогою вмінь \"Зняття посилюючих чар\" або \"Зняття злих чар\". Потрібна стигма.",
		"el_escape": "На всіх членів групи в радіусі 20 м накладається базове маскування. Час дії: [%e1.Hide.RemainTime] Зменшує швидкість пересування. Неможливо використовувати під час бою. Потрібна стигма.",
		"el_ethercharge": "Відновлює 100%% HP елементаля. Потрібна стигма.",
		"el_fireaid": "Ваш персонаж і члени групи в радіусі 20 м завдають ворогам додатково [%e1.Provoker.OtherSkill.e1.ProcATK_Instant.Damage] од. шкоди з ймовірністю [%e1.Provoker.ConditionProb]%%. Необхідна умова: [%e1.Provoker.Condition]. Час дії: [%e1.Provoker.RemainTime] Потрібна стигма.",
		"el_hellcurse": "Змінює наступні параметри цілі: [%e1.StatDown.StatName] -[%e1.StatDown.Value], [%e2.StatDown.StatName] -[%e2.StatDown.Value], [%e2.StatDown.StatName2] -[%e2.StatDown.Value2]. Час дії: [%e1.StatDown.RemainTime] Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"el_hellpain": "Удар магією землі, завдає цілі [%e1.SpellATK_Instant.FixDamage] од. шкоди. Радіус дії: [%First_Target_Valid_Distance] м. Завдає додатково [%e2.SpellATK.Damage] од. шкоди з інтервалом у [%e2.SpellATK.CheckTime] Час дії: [%e2.SpellATK.RemainTime] Можна видалити за допомогою вмінь \"Зняття посилювальних чар\" або \"Зняття злих чар\". Потрібна стигма.",
		"el_manareverse": "Скасовує посилювальну магію на цілі (максимум до [%e1.DispelBuffCounterATK.DispelCount] шт.) При скасуванні одного ефекту завдає [%e1.DispelBuffCounterATK.Damage] од. шкоди. У разі скасування більш ніж одного ефекту завдає по [%e1.DispelBuffCounterATK.AddDamage] од. додаткової шкоди. Ціль додатково отримує [%e2.SkillLauncher.OtherSkill.e1.SpellATK.Damage] од. шкоди з інтервалом у [%e2.SkillLauncher.OtherSkill.e1.SpellATK.CheckTime] Час дії: [%e2.SkillLauncher.OtherSkill.e1.SpellATK.RemainTime] Можна видалити за допомогою вмінь \"Зняття посилювальних чар\" або \"Зняття злих чар\". 1-е вміння в серії Потрібна стигма.",
		"el_order_elementalfield": "Наказує елементалю використовувати посилюючу магію. Діє на всіх союзників в радіусі 15 м. Елементаль води: Збільшує маг. захист і точність. Елементаль вітру: Збільшує точність і ухилення. Елементаль землі: Відновлює HP, знімає фіз./маг. негативні ефекти. Елементаль вогню: Посилює фіз. атаку, відбиває атаку. Елементаль магми: Відновлює HP, збільшує фіз. атаку. Елементаль тайфуну: Збільшує точність магії, маг. захист, точність, шанс ухилення.",
		"el_order_omen": "Наказує елементалю використовувати злі чари, якими володіє сам персонаж. Елементаль, приводячи ціль у стан одержимості, усипляє її, зменшує швидкість її атаки та посилює її захист від усіх стихій, а потім зникає. Потрібна стигма.",
		"el_order_protect": "Наказує елементалю захищати ціль. Елементаль створює навколо цілі магічний бар'єр і отримує замість неї всю завдану їй шкоду з шансом 100%%. Радіус дії: 20 м. Бар'єр діє 20 сек. Потрібна стигма.",
		"el_order_sacrifice": "Наказує елементалю використовувати захисні вміння. Елементаль отримує всю шкоду замість свого господаря. Потрібна стигма.",
		"el_silence": "Накладає на ціль в радіусі [%First_Target_Valid_Distance] м ефект німоти. Час дії: [%e1.Silence.RandomTime]-[%e1.Silence.RemainTime] Потрібна стигма.",
		"el_slave_stormservent_dark": "Атака магією повітря, закликає елементалів вітру ([%e1.SummonHoming.UnitNumber] шт.), які завдають шкоди ворогу в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"el_slave_stormservent_light": "Атака магією повітря, закликає елементалів вітру ([%e1.SummonHoming.UnitNumber] шт.), які завдають шкоди ворогу в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"el_sleepingspirit": "Усипляє ціль. [%e2.StatUp.StatName] збільшується. Час дії: [%e1.Sleep.RemainTime] Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"el_soulsteal": "Удар магією води, завдає цілі в радіусі [%First_Target_Valid_Distance] м [%e1.SpellATK_Instant.FixDamage] од. шкоди. 5 повторів Потрібна стигма.",
		"el_stigma_order_destructimpact": "Наказує елементалю атакувати вміннями. Кожен елементаль атакує тією стихією, частиною якої є. Елементаль води: Атакує магією води. Елементаль вітру: Атакує магією повітря, завдаючи тривалу шкоду. Елементаль землі: Атакує магією землі, завдаючи тривалу шкоду, знижує швидкість руху. Елементаль вогню: Атакує магією вогню. Елементаль магми: Атакує магією вогню. Елементаль тайфуну: Атакує магією повітря. Потрібна стигма.",
		"el_stigma_order_etheremission_light": "Стигма давнього даєва. Наказує елементалю використовувати атакуючі вміння, витрачаючи HP. Кожен елементаль може атакувати власною стихією по площі навколо себе. Якщо мета атаки - асмодіан або балаур, то їй завдається додаткова шкода. Потрібна стигма. Елементаль води: Атакує магією води. Елементаль вітру: Атакує магією повітря. Елементаль землі: Атакує магією землі. Елементаль вогню: Атакує магією вогню. Елементаль тайфуну: Атакує магією води.",
		"el_stigma_order_ethereruption_light": "Наказує елементалю використовувати атакуючі вміння, витрачаючи HP. Кожен елементаль може атакувати власною стихією по площі навколо себе. Якщо ціль атаки - асмодіанець або балаур, то їй завдається додаткова шкода. Потрібна стигма. Елементаль води: Атакує магією води. Елементаль вітру: Атакує магією повітря. Елементаль землі: Атакує магією землі. Елементаль вогню: Атакує магією вогню. Елементаль тайфуну: Атакує магією води.",
		"el_stigma_order_etherimpact_dark": "Стигма давнього даєва. Наказує елементалю використовувати атакуючі вміння, витрачаючи HP. Кожен елементаль може атакувати власною стихією по площі навколо себе. Якщо мета атаки - елій або балаур, то їй завдається додаткова шкода. Потрібна стигма. Елементаль води: Атакує магією води. Елементаль вітру: Атакує магією повітря. Елементаль землі: Атакує магією землі. Елементаль вогню: Атакує магією вогню. Елементаль магми: Атакує магією землі.",
		"el_stigma_order_shadoweruption_dark": "Наказує елементалю використовувати атакуючі вміння, витрачаючи HP. Кожен елементаль може атакувати власною стихією по площі навколо себе. Якщо мета атаки - елієць або балаур, то їй завдається додаткова шкода. Потрібна стигма. Елементаль води: Атакує магією води. Елементаль вітру: Атакує магією повітря. Елементаль землі: Атакує магією землі. Елементаль вогню: Атакує магією вогню. Елементаль магми: Атакує магією землі.",
		"el_stigma_stormblade": "Удар магією повітря, завдає цілі [%e1.SpellATK_Instant.FixDamage] од. шкоди та [%e2.SpellATK.Damage] од. шкоди з інтервалом в [%e2.SpellATK.CheckTime] Радіус дії: [%First_Target_Valid_Distance] м. Час дії: [%e2.SpellATK.RemainTime] Потрібна стигма.",
		"el_sympatheticswitch": "Ворожість цілі до персонажа змінюється на ворожість до елементаля. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"el_terrorspirit": "Перетворює ворогів в радіусі 15 м в елементалів вогню, змушує їх до втечі та знижує їх швидкість руху на [%e1.Fear.RandomTime]-[%e1.Fear.RemainTime] Потрібна стигма.",
		"fi_anklegrab": "Знерухомлює ціль, що знаходиться в радіусі [%First_Target_Valid_Distance] м. [%e2.StatDown.StatName] цілі -[%e2.StatDown.Value]. Час дії: [%e1.Root.RemainTime] Потрібна стигма.",
		"fi_anklesnatcher": "Знеструмлює ціль. Радіус дії: [%First_Target_Valid_Distance] м. Час дії: [%e1.Root.RemainTime] Потрібна стигма.",
		"fi_berserkstance": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%%. При цьому [%e2.StatDown.StatName] -[%e2.StatDown.Value], а [%e3.StatDown.StatName] -[%e3.StatDown.Value]%%. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"fi_blademode": "При нападі на іншого персонажа шкода збільшується на 25%%, а [%e2.StatBoost.StatName] - на [%e2.StatBoost.FixValue]. Активне вміння Потрібна стигма.",
		"fi_burserklance": "З ймовірністю 100%% завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. фізичної шкоди. 1-е вміння в серії Потрібна стигма.",
		"fi_burserklance_2": "Завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. фізичної шкоди. 1-е вміння в серії Потрібна стигма.",
		"fi_burserklance_3": "З ймовірністю 100%% завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. фізичної шкоди. 1-е вміння в серії Потрібна стигма.",
		"fi_charginghit": "Обов'язково потрапляє в ціль і завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. фізичної шкоди. Потрібна стигма.",
		"fi_charginghit_2": "Завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. фізичної шкоди. Потрібна стигма.",
		"fi_charginghit_3": "Обов'язково потрапляє в ціль і завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. фізичної шкоди. Потрібна стигма.",
		"fi_chargingshock": "Широкий мах зброєю, в радіусі 7 м завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Вражає до 6 цілей. З певною ймовірністю вводить ціль у стан [%e1.SkillATK_Instant.AddEffect]. 1-е вміння в серії Потрібна стигма.",
		"fi_chargingshock_2": "Широкий мах зброєю, в радіусі 7 м завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. 1-е вміння в серії Потрібна стигма.",
		"fi_chargingshock_3": "Широкий мах зброєю, в радіусі 7 м завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Вражає до 6 цілей. З певною ймовірністю вводить ціль у стан [%e1.SkillATK_Instant.AddEffect]. 1-е вміння в серії Потрібна стигма.",
		"fi_cripplingcut": "Фізична атака, завдає впавшому ворогу [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Потрібна стигма.",
		"fi_drainsword": "Завдає цілі [%e1.SkillATKDrain_Instant.MinDamage]-[%e1.SkillATKDrain_Instant.MaxDamage] од. фізичної шкоди. З певною ймовірністю переводить [%e1.SkillATKDrain_Instant.HPHeal]%% нанесеного шкоди в HP. 3-е вміння в серії Рубаючий удар - Меч вампіра Потрібна стигма.",
		"fi_enfeeblehit": "Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. [%e2.StatDown.StatName] -[%e2.StatDown.Value]. [%e3.StatDown.StatName] -[%e3.StatDown.Value]. Час дії: [%e2.StatDown.RemainTime] 1-е вміння в серії Потрібна стигма.",
		"fi_heavyimpact": "Фізична атака, завдає сусупротивникам в радіусі 10 м [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди і знижує їх швидкість руху. Час дії: [%e2.Snare.RandomTime]-[%e2.Snare.RemainTime] Потрібна стигма.",
		"fi_howling": "[%e1.StatDown.StatName] ворогів в радіусі 7 м знижується на [%e1.StatDown.Value]. Час дії: [%e1.StatDown.RemainTime] Потрібна стигма.",
		"fi_jumpattack": "Здійснює ривок до супротивника в радіусі [%First_Target_Valid_Distance] м і завдає йому [%e1.DashATK.MinDamage]-[%e1.DashATK.MaxDamage] од. шкоди. Потрібна стигма.",
		"fi_kneecrash": "Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди та знерухомлює її на [%e2.Root.RemainTime] Потрібна стигма.",
		"fi_lockdownimpact": "Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Забороняє цілі використовувати фізичні вміння. Час дії: [%e2.Bind.RemainTime] Потрібна стигма.",
		"fi_magicalbarrier": "Скасування магії +[%e1.StatUp.Value]. Маг. захист -[%e2.StatDown.Value]. Час дії: [%e1.StatUp.RemainTime]",
		"fi_potentialhealth": "Відновлює [%e1.Heal_Instant.Heal]%% HP протягом [%e2.StatUp.RemainTime] [%e2.StatUp.StatName] +[%e2.StatUp.Value]%%. [%e3.StatUp.StatName] +[%e3.StatUp.Value]. [%e4.StatUp.StatName] +[%e4.StatUp.Value]. Потрібна стигма.",
		"fi_ragespirit": "Створює захисний бар'єр, що блокує шкоди з ймовірністю [%e1.Shield.ConditionProb]%%. Необхідна умова: [%e1.Shield.Condition]. Час дії: [%e1.Shield.RemainTime] (Захисний бар'єр зберігається до нанесення персонажу [%e1.Shield.CoverValue] од. шкоди.) Потрібна стигма.",
		"fi_revengeslash": "Після успішного парирування завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. фізичної шкоди. Потрібна стигма.",
		"fi_seismicdrain": "Завдає [%e1.SkillATKDrain_Instant.MinDamage]-[%e1.SkillATKDrain_Instant.MaxDamage] од. шкоди в радіусі 7 м. Перетворює [%e1.SkillATKDrain_Instant.HPHeal]%% завданої шкоди в HP. 1-е вміння в серії Потрібна стигма.",
		"fi_sharpnesshit": "Завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. фізичної шкоди. 1-е вміння в серії Потрібна стигма.",
		"fi_spinningparry": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"fi_stigma_draincut": "Фізична атака, завдає поваленій цілі [%e1.SkillATKDrain_Instant.MinDamage]-[%e1.SkillATKDrain_Instant.MaxDamage] од. шкоди. Переводить [%e1.SkillATKDrain_Instant.HPHeal]%% завданої шкоди в HP. Потрібна стигма.",
		"fi_stigma_forceblast_light": "Стигма давнього даєва. Фізична атака, завдає цілям в радіусі [%First_Target_Valid_Distance] м та 5 супротивникам в радіусі 10 м від цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. [%e2.StatDown.StatName] цілей -[%e2.StatDown.Value] на [%e2.StatDown.RemainTime] Потрібна стигма.",
		"fi_stigma_forceburst_light": "Фізична атака, завдає цілі в радіусі [%First_Target_Valid_Distance] м та 18 сусупротивникам в радіусі 10 м від цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. [%e2.StatDown.StatName] цілей -[%e2.StatDown.Value] на [%e2.StatDown.RemainTime] Потрібна стигма.",
		"fi_stigma_shockburst_dark": "Фізична атака, завдає 18 ворогам в радіусі 10 м [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. [%e2.StatDown.StatName] цілей -[%e2.StatDown.Value] на [%e2.StatDown.RemainTime] Потрібна стигма.",
		"fi_stigma_shockimpulse_dark": "Стигма давнього даєва. Фізична атака, завдає 12 ворогам в радіусі 10 м [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. [%e2.StatDown.StatName] цілей -[%e2.StatDown.Value] на [%e2.StatDown.RemainTime] Потрібна стигма.",
		"fi_survivorstance": "Відновлює [%e1.Heal_Instant.Heal]%% HP. [%e2.StatUp.StatName] +[%e2.StatUp.Value]%%. [%e3.StatUp.StatName] +[%e3.StatUp.Value]. Час дії: [%e2.StatUp.RemainTime] Потрібна стигма.",
		"fi_technicalcounter": "Фізична атака, після успішного парирування завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Вводить ціль у стан [%e1.SkillATK_Instant.AddEffect]. Потрібна стигма.",
		"fi_vorpalhit": "Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. 2-е вміння в серії Колючий удар - Рубаючий удар Потрібна стигма.",
		"fi_whirldrain": "Завдає [%e1.SkillATKDrain_Instant.MinDamage]-[%e1.SkillATKDrain_Instant.MaxDamage] од. шкоди в радіусі 7 м. Переводить [%e1.SkillATKDrain_Instant.HPHeal]%% завданої шкоди в HP. 3 повтори 1-е вміння в серії Потрібна стигма.",
		"fi_whirltornado": "Завдає [%e1.SkillATKDrain_Instant.MinDamage]-[%e1.SkillATKDrain_Instant.MaxDamage] од. шкоди в радіусі 7 м. Переводить [%e1.SkillATKDrain_Instant.HPHeal]%% завданої шкоди в HP. 2-е вміння в серії Виснажуюча хвиля (х3) - Відновлювальна хвиля Потрібна стигма.",
		"gu_antigravitycannon": "Магічна атака землі, завдає цілі [%e1.SpellATK_Instant.FixDamage] од. ушкодження та вводить її в стан [%e1.SpellATK_Instant.AddEffect]. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"gu_armorbreak": "Удар магією повітря, завдає [%e1.SpellATK_Instant.FixDamage] од. ушкодження цілі в радіусі [%First_Target_Valid_Distance] м. [%e2.StatDown.StatName] -[%e2.StatDown.Value]%. Ефективність магії лікування -50%. Час дії: [%e2.StatDown.RemainTime] Потрібна стигма.",
		"gu_bullseye": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"gu_empowerammo": "Завдає цілі додатково [%e1.Provoker.OtherSkill.e1.ProcATK_Instant.Damage] од. шкоди з ймовірністю [%e1.Provoker.ConditionProb]%%. Зменшує силу атаки персонажа. Необхідна умова: [%e1.Provoker.Condition]. Час дії: [%e1.Provoker.RemainTime] Потрібна стигма.",
		"gu_empowermagic": "Підвищує дію [%e1.OneTimeBoostSkillAttack.AttackType] на [%e1.OneTimeBoostSkillAttack.BonusRate]%%. Підвищує силу атаки проти персонажів на 5 атак або на [%e1.OneTimeBoostSkillAttack.RemainTime].&#xD; Потрібна стигма.",
		"gu_firechainrefresh": "Скидає час перезарядки вмінь \"Стрільба з пістолета\", \"В яблучко\", \"Розсікаючий вогонь\". Потрібна стигма.",
		"gu_flamecannon": "Удар магією вогню, завдає цілі в радіусі [%First_Target_Valid_Distance] м [%e1.SpellATK_Instant.FixDamage] од. шкоди. При цьому її [%e2.StatDown.StatName] зменшується на [%e2.StatDown.Value]%. Час дії: [%e2.StatDown.RemainTime] Потрібна стигма.",
		"gu_flamecannon_2": "Удар магією вогню, завдає цілі в радіусі [%First_Target_Valid_Distance] м [%e1.SpellATK_Instant.FixDamage] од. шкоди. При цьому її [%e2.StatDown.StatName] зменшується на [%e2.StatDown.Value]%. Час дії: [%e2.StatDown.RemainTime] Потрібна стигма.",
		"gu_flamecannon_3": "Удар магією вогню, завдає цілі в радіусі [%First_Target_Valid_Distance] м [%e1.SpellATK_Instant.FixDamage] од. шкоди. При цьому її [%e2.StatDown.StatName] зменшується на [%e2.StatDown.Value]%. Час дії: [%e2.StatDown.RemainTime] Потрібна стигма.",
		"gu_icecannon": "Удар магією води, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди в радіусі [%First_Target_Valid_Distance] м. Знерухомлює супротивника на [%e2.Root.RemainTime] Потрібна стигма.",
		"gu_magicalbreathing": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"gu_mentaliccannon": "Удар магією вітру, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. MP -[%e2.MPAttack_Instant.Damage]%%. Потрібна стигма.",
		"gu_mentaliccannon_2": "Удар магією вітру, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. MP -[%e2.MPAttack_Instant.Damage]%%. Потрібна стигма.",
		"gu_mentaliccannon_3": "Удар магією вітру, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. MP -[%e2.MPAttack_Instant.Damage]%%. Потрібна стигма.",
		"gu_mentalsnatcher": "Атака магією води, завдає [%e1.SpellATKDrain_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. Переводить [%e1.SpellATKDrain_Instant.HPHeal]%% завданої шкоди в HP і [%e1.SpellATKDrain_Instant.MPHeal]%% - в MP. Потрібна стигма.",
		"gu_onepointrapidfire": "Удар магією землі, завдає цілі в радіусі [%First_Target_Valid_Distance] м [%e1.SpellATK_Instant.FixDamage] од. шкоди. 5 повторів Потрібна стигма.",
		"gu_rapidstance": "[%e1.StatBoost.StatName] +[%e1.StatBoost.RateValue]%%. Потрібна стигма. Активне вміння",
		"gu_shockcannon": "Удар магією повітря, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. Оглушає супротивника на [%e2.Stun.RemainTime] Потрібна стигма.",
		"gu_shockcannon_2": "Магічна атака вітром, завдає цілі та 2 супротивникам в радіусі 2 м від неї [%e1.SpellATK_Instant.FixDamage] од. шкоди і відштовхує їх. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"gu_shockcannon_3": "Магічна атака вітром, завдає цілі та 3 супротивникам в радіусі 4 м від неї [%e1.SpellATK_Instant.FixDamage] од. шкоди і відштовхує їх на 4 сек. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"gu_silenceshot": "Магічна атака вітром, завдає цілі [%e1.SpellATK_Instant.FixDamage] од. шкоди та викликає німоту. Час дії: [%e2.Silence.RandomTime]-[%e2.Silence.RemainTime] Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"gu_soulbreakcannon": "Удар магією води, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"gu_soulbreakcannon_2": "Удар магією води, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"gu_soulbreakcannon_3": "Удар магією води, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"gu_sunningshot": "Удар магією вогню, завдає цілі [%e1.SpellATK_Instant.FixDamage] од. шкоди та оглушає її на [%e2.Stun.RemainTime]. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"gu_survivalinstinct": "Скасовує 2 негативних фізичних ефекти. [%e2.StatUp.StatName]% +[%e2.StatUp.Value]%%. Час дії: [%e2.StatUp.RemainTime] Потрібна стигма.",
		"gu_vassblaster": "Удар магією вогню, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м від вашого персонажа та 3 сусупротивникам в радіусі 10 м від вибраної цілі. Потрібна стигма.",
		"gu_vassblaster_2": "Удар магією вогню, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м від вашого персонажа та 4 сусупротивникам в радіусі 10 м від вибраної цілі. Потрібна стигма.",
		"gu_vassblaster_3": "Удар магією вогню, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м від вашого персонажа та 5 сусупротивникам в радіусі 10 м від вибраної цілі. Потрібна стигма.",
		"gu_veinsnipe": "Удар магією землі, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. Також викликає кровотечу на [%e2.Bleed.RemainTime] Потрібна стигма.",
		"kn_absolutescare": "Провокує максимум 4 сусупротивників в радіусі 10 м та збільшує їх ворожість, піддаючи їх страху та знижуючи швидкість руху. Час дії: [%e2.Fear.RemainTime] Потрібна стигма.",
		"kn_brainstorm": "Удар магією землі, завдає цілі [%e1.SpellATK_Instant.FixDamage] од. шкоди і оглушає її на [%e2.Stun.RemainTime] Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"kn_breakpower": "Фізична атака, завдає впавшій цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. [%e2.StatDown.StatName] цілі -[%e2.StatDown.Value]. Час дії: [%e2.StatDown.RemainTime] [%e0.KN_BreakPower_G1_Buff.e1.StatUp.StatName] +[%e0.KN_BreakPower_G1_Buff.e1.StatUp.Value]. Потрібна стигма.",
		"kn_conquestmind": "Відновлює [%e1.Heal.CheckTimeHeal] HP вашого персонажа з інтервалом у [%e1.Heal.CheckTime] Час дії: [%e1.Heal.RemainTime] Потрібна стигма.",
		"kn_destructshield": "Гарантовано завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. фізичної шкоди і перекидає її. Необхідний щит. Потрібна стигма.",
		"kn_destructwish": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%%. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. [%e3.StatUp.StatName] +[%e3.StatUp.Value]. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"kn_divinepower": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%%. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"kn_divineslash": "Фізична атака, завдає сусупротивнику [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Потрібна стигма.",
		"kn_executionalstrike": "Завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. фізичної шкоди. Потрібна стигма.",
		"kn_fortitudewave": "Завдає максимум 6 супротивникам в радіусі 7 м навколо себе [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. фізичної шкоди і знерухомлює їх на [%e2.Root.RemainTime] Потрібна стигма.",
		"kn_grandprotection": "Ви отримуєте [%e1.Protect.Value]%% шкоди замість члена вашої групи. Необхідна умова: [%e1.Protect.Condition] на союзника. Радіус дії: [%e1.Protect.Range] м. Час дії: [%e1.Protect.RemainTime] Потрібна стигма.",
		"kn_highprovoke": "Провокує ціль на відстані [%First_Target_Valid_Distance] м і збільшує ворожість цілі до персонажа. Ефект підвищеної ворожості діє 5 сек. Потрібна стигма.",
		"kn_holywrath": "Відбиває [%e1.Reflector.FixedDamage] од. шкоди назад в супротивника. Необхідна умова: [%e1.Reflector.Condition] на вашого персонажа. Радіус дії: [%e1.Reflector.MaxRange] м. Час дії: [%e1.Reflector.RemainTime] Потрібна стигма.",
		"kn_intimidation": "Провокує ціль на відстані [%First_Target_Valid_Distance] м, збільшує ворожість цілі до персонажа і на короткий час зменшує швидкість атаки ворога. Потрібна стигма.",
		"kn_invinsibleprotect": "Створює захисний бар'єр, здатний з ймовірністю [%e1.Shield.ConditionProb]%% блокувати шкоди. Необхідна умова: [%e1.Shield.Condition] на персонажа або членів його групи в радіусі 30 м навколо нього. Час дії: [%e1.Shield.RemainTime] [%e2.StatUp.StatName] +[%e2.StatUp.Value]. (Захисний бар'єр може на [%e1.Shield.CoverValue]%% блокувати шкоди, наносимий персонажу за 1 раз.) Потрібна стигма.",
		"kn_invinsibleshield": "Блокує щитом атаки супротивника. Кількість блокувань: [%e1.AlwaysBlock.Count]. Час дії: [%e1.AlwaysBlock.RemainTime] Необхідний щит. Потрібна стигма.",
		"kn_massiveprovoke": "Провокує від 1 до 5 цілей, насміхаючись над ними. Радіус дії: 10 м. Потрібна стигма.",
		"kn_movingstance": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]%%. [%e1.StatUp.StatName3] +[%e1.StatUp.Value3]. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. [%e2.StatUp.StatName2] +[%e2.StatUp.Value2]. [%e2.StatUp.StatName3] +[%e2.StatUp.Value3]. Використання інших вмінь перериває дію цього вміння. Неможливо виконувати стрибки. Необхідний щит. Активне вміння Потрібна стигма.",
		"kn_powersink": "Удар магією землі, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. 3-е вміння в серії Критичний удар - Руйнівний магічний удар Потрібна стигма.",
		"kn_recover": "Відновлює [%e1.Heal_Instant.Heal] HP. Потрібна стигма.",
		"kn_reflectshield": "[%e2.StatBoost.StatName] +[%e2.StatBoost.FixValue]. [%e3.StatBoost.StatName] +[%e3.StatBoost.RateValue]%%. [%e4.StatBoost.StatName] +[%e4.StatBoost.FixValue]. Відбиває [%e1.Reflector.FixedDamage] од. шкоди у ворога, що використовує дію [%e1.Reflector.Condition] на вашого персонажа, в радіусі [%e1.Reflector.MaxRange] м. Використання інших умінь перериває дію цього вміння, неможливо виконувати стрибки. Необхідний щит. Активне вміння Потрібна стигма.",
		"kn_revivaltouch": "Відновлює за рахунок своїх HP [%e1.Heal_Instant.Heal] HP цілі в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"kn_sentinel": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Діє на вас і 6 ваших союзників в радіусі 30 м від вас. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"kn_stigma_demonpunishment_dark": "Завдає цілі [%e1.SkillATKDrain_Instant.MinDamage]-[%e1.SkillATKDrain_Instant.MaxDamage] од. шкоди. Переводить [%e1.SkillATKDrain_Instant.HPHeal]%% завданої шкоди в HP. Потрібна стигма.",
		"kn_stigma_drainsword_dark": "Стигма давнього даєва. Завдає цілі [%e1.SkillATKDrain_Instant.MinDamage]-[%e1.SkillATKDrain_Instant.MaxDamage] од. шкоди. Переводить [%e1.SkillATKDrain_Instant.HPHeal]%% нанесеної шкоди в HP. Потрібна стигма.",
		"kn_stigma_godjudgement_light": "Стигма давнього даєва. Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди та оглушує її. Час дії: [%e2.Stun.RemainTime] Потрібна стигма.",
		"kn_stigma_godpunishment_light": "Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди та оглушає її. Час дії: [%e2.Stun.RemainTime] Потрібна стигма.",
		"kn_stigma_resistarmor": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"kn_stunningsnacher": "Притягує ворога в радіусі [%First_Target_Valid_Distance] м до персонажа, збільшує його ворожість і знижує його швидкість руху. Час дії: [%e2.Snare.RemainTime] Потрібна стигма.",
		"kn_thunderblade": "Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"kn_triplesnacher": "Притягує ціль і ще 2 ворогів в радіусі [%First_Target_Valid_Distance] м до персонажа, збільшує їх ворожість і знижує їх швидкість руху. Час дії: [%e2.Snare.RemainTime] Потрібна стигма.",
		"p_equip_dual": "Покращує майстерність володіння парним зброєю.",
		"pr_bindingheal": "Відновлює [%e1.Heal_Instant.Heal] HP вашого персонажа та вибраного члена вашої групи, що знаходиться в радіусі [%First_Target_Valid_Distance] м. Діє лише на членів вашої групи. Потрібна стигма.",
		"pr_blindinglight": "Ослеплює ціль. Час дії: [%e1.Blind.RemainTime] Потрібна стигма.",
		"pr_calllightning": "Удар магією повітря, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"pr_coursewound": "Удар магією води, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди в радіусі [%First_Target_Valid_Distance] м. Знижує отриманий ціллю ефект магічного відновлення на 50%%. Час дії: [%e2.DeboostHealAmount.RemainTime] Потрібна стигма.",
		"pr_eternalservent_dark": "Закликає святу міць. Дух не може рухатися. Атакує ціль в радіусі 30 м, завдаючи дистанційно [%e0.EternalServent_G1.e1.SpellATK_Instant.FixDamage] од. шкоди магією вогню. Зникає через деякий час. При кожній атаці витрачає свої HP. Потрібна стигма.",
		"pr_eternalservent_light": "Закликає святу міць. Дух не може рухатися. Атакує ціль в радіусі 30 м, завдаючи дистанційно [%e0.EternalServent_G1.e1.SpellATK_Instant.FixDamage] од. шкоди магією вогню. Зникає через деякий час. При кожній атаці витрачає свої HP. Потрібна стигма.",
		"pr_firstaid": "Відновлює [%e1.Heal_Instant.Heal] HP цілі в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"pr_graceofgod": "Дозволяє застосовувати вміння без витрат MP. Час дії: [%e1.BoostSkillCost.RemainTime] Потрібна стигма.",
		"pr_healershand": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Під час дії вміння витрата МР збільшується на 10%%. Активне вміння Потрібна стигма.",
		"pr_healinggrace": "На 50%% збільшує ефект відновлення у членів групи в радіусі 25 м від що виголошує заклинання. Час дії: [%e1.DeboostHealAmount.RemainTime] Потрібна стигма.",
		"pr_healingservent_dark": "Закликає духа зцілення. Дух нерухомий. Діє на персонажів в радіусі 30 метрів і відновлює HP 6 членів альянсу на [%e0.PR_Dark_Totem_HealingServent_G1.e1.Heal_Instant.Heal]. Дух зникає через певний час. Потрібна стигма.",
		"pr_healingservent_light": "Закликає духа зцілення. Дух нерухомий. Діє на персонажів в радіусі 30 метрів і відновлює HP 6 членів альянсу на [%e0.PR_Light_Totem_HealingServent_G1.e1.Heal_Instant.Heal]. Дух зникає через певний час. Потрібна стигма.",
		"pr_massdispel": "Знімає всі злі чари з вашого персонажа та членів вашої групи, що знаходяться в радіусі 25 м. Потрібна стигма.",
		"pr_massemergentheal": "Відновлює [%e1.Heal_Instant.Heal] HP персонажа та членів групи. Радіус дії: 25 м. Потрібна стигма.",
		"pr_memoryblur": "Зменшує ворожість цілі до персонажа. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"pr_offensivemode": "[%e1.StatBoost.StatName] +[%e1.StatBoost.FixValue]. [%e2.StatBoost.StatName] +[%e2.StatBoost.FixValue]. [%e3.StatDown.StatName] -150. Активне вміння Потрібна стигма.",
		"pr_painlinks": "Удар магією землі, завдає цілі [%e1.SpellATK_Instant.FixDamage] од. шкоди. Радіус дії: [%First_Target_Valid_Distance] м. Завдає додатково [%e2.SpellATK.Damage] од. шкоди з інтервалом у [%e2.SpellATK.CheckTime]. Час дії: [%e2.SpellATK.RemainTime] [%e4.StatDown.StatName] -[%e4.StatDown.Value]. Якщо ціль помре під час дії ефекту, вона відродиться у свого кібелиска або ники. Потрібна стигма.",
		"pr_powersmite": "Удар магією землі, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди в радіусі [%First_Target_Valid_Distance] м. 1-е вміння в серії Потрібна стигма.",
		"pr_purgatory": "Удар магією землі, завдає цілі [%e1.SpellATK_Instant.FixDamage] од. шкоди і [%e2.SpellATK.Damage] од. шкоди з інтервалом у [%e2.SpellATK.CheckTime]. Радіус дії: [%First_Target_Valid_Distance] м. Час дії: [%e2.SpellATK.RemainTime] Потрібна стигма.",
		"pr_regeneraitionshine": "Відновлює [%e1.Heal_Instant.Heal] HP цілі в радіусі [%First_Target_Valid_Distance] м, а також додатково відновлює [%e2.Heal.CheckTimeHeal] HP з інтервалом у [%e2.Heal.CheckTime] [%e3.StatUp.StatName] +[%e3.StatUp.Value]. Час дії: [%e2.Heal.RemainTime] Потрібна стигма.",
		"pr_restorelife": "Відновлює [%e1.CaseHeal.Heal] од. HP цілі, якщо вони знизяться до 50%% і нижче. Час дії: 1 хв. Потрібна стигма.",
		"pr_reversecondition": "Міняє місцями ваші MP та HP. Потрібна стигма.",
		"pr_revivehand": "Благословляє члена групи, що знаходиться в радіусі [%First_Target_Valid_Distance] м. Час дії: [%e1.Rebirth.RemainTime]. При смерті під час дії вміння ціль воскресає з [%e1.Rebirth.CurrentHPMP]%% HP і MP. Потрібна стигма.",
		"pr_sageswisdom": "Зменшує час підготовки вмінь на [%e1.BoostSkillCastingTime.CastingBonus]%%. Час дії: [%e1.BoostSkillCastingTime.RemainTime] Потрібна стигма.",
		"pr_sprint": "Підвищує швидкість руху на 30%%. Максимальний час дії: 10 сек. Потрібна стигма.",
		"pr_stigma_abysalcircle_dark": "Стигма давнього даєва. Відновлює [%e1.Heal_Instant.Heal] HP мети в радіусі [%First_Target_Valid_Distance] м і HP 6 союзників в радіусі 25 м від мети. Також створює захисний бар'єр, що запобігає шкоді на [%e2.Shield.CoverValue] кожного разу при отриманні [%e2.Shield.Condition]. Максимум запобігаємої шкоди: [%e2.Shield.ShieldValue]. Час дії: [%e2.Shield.RemainTime] Потрібна стигма.",
		"pr_stigma_abysalsanctuary_dark": "Відновлює [%e1.Heal_Instant.Heal] HP цілі в радіусі [%First_Target_Valid_Distance] м та 6 союзникам в радіусі 25 м від цілі. Також створює захисний бар'єр, що запобігає шкоді на [%e2.Shield.CoverValue] щоразу, коли на персонажа проводиться [%e2.Shield.Condition]. Максимум запобігаємої шкоди: [%e2.Shield.ShieldValue]. Час дії: [%e2.Shield.RemainTime] Потрібна стигма.",
		"pr_stigma_divinecircle_light": "Стигма давнього даєва. Відновлює [%e1.Heal_Instant.Heal] HP мети в радіусі [%First_Target_Valid_Distance] м і 6 союзників в радіусі 25 м від мети, а також додатково відновлює [%e2.Heal.CheckTimeHeal] HP з інтервалом у [%e2.Heal.CheckTime] Час дії: [%e2.Heal.RemainTime] Потрібна стигма.",
		"pr_stigma_divinesanctuary_light": "Відновлює [%e1.Heal_Instant.Heal] HP цілі в радіусі [%First_Target_Valid_Distance] м та 6 союзникам в радіусі 25 м від цілі, а також додатково відновлює [%e2.Heal.CheckTimeHeal] HP з інтервалом в [%e2.Heal.CheckTime] Час дії: [%e2.Heal.RemainTime] Потрібна стигма.",
		"pr_stigma_suggestion": "Зменшує ворожість цілі та 6 ворогів в радіусі 20 м від неї до персонажа. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"pr_suffermemory": "Удар магією повітря, завдає цілі [%e1.SpellATK_Instant.FixDamage] од. шкоди одразу, потім завдає по [%e2.SpellATK.Damage] од. шкоди магією землі протягом [%e2.SpellATK.RemainTime] з інтервалом у [%e2.SpellATK.CheckTime] [%e3.StatDown.StatName] цілі -[%e3.StatDown.Value]. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"pr_thunderofpunishment": "Удар магією повітря, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"pr_tranquility": "Знімає до 3 злих чар з персонажа і 6 його союзників у радіусі 20 м, а також відновлює [%e2.Heal.CheckTimeHeal] HP. Потрібна стигма.",
		"ra_backdashstab": "Завдає супротивнику [%e1.BackDashATK.MinDamage]-[%e1.BackDashATK.MaxDamage] од. шкоди, відштовхуючи вашого персонажа на 25 м назад. Дає шанс оглушити супротивника на [%e2.Stun.RemainTime] Потрібна стигма.",
		"ra_blazingtrap_dark": "Для встановлення пастки потрібно 20 насіння трипіда. При наближенні ворога міна вибухає. Радіус дії: 5 м. Час дії пастки: [%e1.SummonTrap.SummonTime] Потрібна стигма.",
		"ra_blazingtrap_light": "Для встановлення пастки потрібно 20 насіння трипіда. При наближенні ворога міна вибухає. Радіус дії: 5 м. Час дії пастки: [%e1.SummonTrap.SummonTime] Потрібна стигма.",
		"ra_breathofnature": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"ra_callcompanion_dark": "Закликає симургів ([%e1.SummonHoming.UnitNumber] шт.), які завдають фізичної шкоди супротивникам у радіусі [%First_Target_Valid_Distance] м. Кожна атака симурга знижує швидкість руху цілі. Потрібна стигма.",
		"ra_callcompanion_light": "Закликає симургів ([%e1.SummonHoming.UnitNumber] шт.), які завдають фізичної шкоди супротивникам у радіусі [%First_Target_Valid_Distance] м. Кожна атака симурга знижує швидкість руху цілі. Потрібна стигма.",
		"ra_draineye": "При кожній атаці протягом [%e1.Provoker.RemainTime] є ймовірність [%e1.Provoker.ConditionProb]%% відновити MP персонажа. Потрібна стигма.",
		"ra_enchantbow": "[%e1.WeaponStatUp.StatName] +[%e1.WeaponStatUp.Value]%%. Зброя: [%e1.WeaponStatUp.WeaponCategory]. Час дії: [%e1.WeaponStatUp.RemainTime] Потрібна стигма.",
		"ra_explosionarrow": "Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ra_fairyflare_dark": "Ставить дистанційну пастку в радіусі [%First_Target_Valid_Distance] м. При наближенні ворога пастка вибухає і знімає з нього маскування. Час дії пастки: [%e1.SummonTrap.SummonTime] Радіус дії: 10 м. Потрібна стигма.",
		"ra_fairyflare_light": "Ставить дистанційну пастку в радіусі [%First_Target_Valid_Distance] м. При наближенні ворога пастка вибухає і знімає з нього маскування. Час дії пастки: [%e1.SummonTrap.SummonTime] Радіус дії: 10 м. Потрібна стигма.",
		"ra_heavenstrap_dark": "Для встановлення пастки потрібно 3 насіння трипіда. При наближенні ворога пастка вибухає, і ціль потрапляє в повітряні окови. Час дії пастки: [%e1.SummonTrap.SummonTime] Радіус дії: 5 м. Потрібна стигма.",
		"ra_heavenstrap_light": "Для встановлення пастки потрібно 3 насіння трипіда. При наближенні ворога пастка вибухає, і ціль потрапляє в повітряні окови. Час дії пастки: [%e1.SummonTrap.SummonTime] Радіус дії: 5 м. Потрібна стигма.",
		"ra_huntermind": "Після використання вміння атакує критичним ударом. Кількість атак: [%e1.OneTimeBoostSkillCritical.BoostCount]. Час дії: [%e1.OneTimeBoostSkillCritical.RemainTime] [%e2.WeaponStatUp.StatName] зменшується на 5 м. Зброя: [%e2.WeaponStatUp.WeaponCategory]. Потрібна стигма.",
		"ra_instantsprint": "Знімає всі ефекти, пов'язані з переміщенням, і миттєво переміщує на 10 м вперед. Потрібна стигма.",
		"ra_lightningshot": "Фізична атака, завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м і оглушає її. Потрібна стигма.",
		"ra_marksmanmode": "[%e1.WeaponStatBoost.StatName] +[%e1.WeaponStatBoost.RateValue]%%. Зброя: [%e1.WeaponStatBoost.WeaponCategory]. У цей час ви пересуваєтеся дуже повільно. Активне вміння Потрібна стигма.",
		"ra_massexplosionarrow": "Фізична атака, завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ra_movingshot": "Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ra_painarrow": "Посилає стрілу в ціль в радіусі [%First_Target_Valid_Distance] м, завдає їй [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] фізичної шкоди і отруює її на [%e2.Poison.RemainTime] Потрібна стигма.",
		"ra_panthermove": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%%. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. [%e3.WeaponStatUp.StatName] +[%e3.WeaponStatUp.Value]%%. Потрібна зброя: [%e3.WeaponStatUp.WeaponCategory]. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"ra_paralyzearrow": "Усипляє ціль в радіусі [%First_Target_Valid_Distance] м. Час дії: [%e1.Sleep.RemainTime] Однак [%e2.StatUp.StatName] збільшується на [%e2.StatUp.Value]. Потрібна стигма.",
		"ra_rapidshot": "Фізична атака, завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди оглушеній, перекинутій або повернутій цілі; цілі, яку відштовхнули або закували в повітряні окови. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ra_resistmind": "Знімає одні злі чари та розсіює шкоду від магії. Кількість разів: [%e2.AlwaysResist.Count]. Час дії: [%e2.AlwaysResist.RemainTime] Потрібна стигма.",
		"ra_sealingarrow": "Завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. ушкодження. Радіус дії: [%First_Target_Valid_Distance] м. На [%e2.BoostSkillCastingTime.RandomTime]-[%e2.BoostSkillCastingTime.RemainTime] збільшує час підготовки вмінь на 100%% і зменшує швидкість атаки. Потрібна стигма.",
		"ra_shadowarrow": "Фізична атака, завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди з великим шансом критичної атаки. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ra_silentarrow": "Фізична атака, завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м і вводить її в стан німоти. Час дії: [%e2.Silence.RandomTime]-[%e2.Silence.RemainTime] Потрібна стигма.",
		"ra_snakebitetrap_dark": "Встановлює пастку біля персонажа. При наближенні супротивника пастка вибухає, завдаючи шкоду 4 ворогам і заковуючи їх у повітряні окови. Час дії пастки: [%e1.SummonTrap.SummonTime] Радіус дії: 10 м. Потрібна стигма.",
		"ra_snakebitetrap_light": "Встановлює пастку біля персонажа. При наближенні супротивника пастка вибухає, завдаючи шкоду 4 ворогам і заковуючи їх у повітряні окови. Час дії пастки: [%e1.SummonTrap.SummonTime] Радіус дії: 10 м. Потрібна стигма.",
		"ra_spoutarrow": "Фізична атака, завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди меті та 6 супротивникам, що знаходяться на відстані до 7 м від неї. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ra_stigma_ancientarrow_light": "Фізична атака з невеликою точністю, завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ra_stigma_destructarrow_dark": "Стигма давнього даєва. Фізична атака з невеликою точністю, завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ra_stigma_mysticarrow_dark": "Фізична атака з невеликою точністю, завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ra_stigma_phoenixarrow_light": "Стигма давнього даєва. Фізична атака з невеликою точністю, завдає [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ra_stigma_tigereye": "[%e1.WeaponStatUp.StatName] -10 м. [%e2.WeaponStatUp.StatName] +[%e2.WeaponStatUp.Value]%%. [%e3.WeaponStatUp.StatName] +[%e3.WeaponStatUp.Value]%%. Зброя: [%e1.WeaponStatUp.WeaponCategory]. Час дії: [%e1.WeaponStatUp.RemainTime] Потрібна стигма.",
		"ra_throwingtrap_dark": "Для встановлення пастки необхідно 3 насіння трипіда. При активації пастки ціль знерухомлюється, її здатність до ухилення знижується. Час дії: [%e1.SummonTrap.SummonTime] Радіус дії: 5 м. Потрібна стигма.",
		"ra_throwingtrap_light": "Для встановлення пастки необхідно 3 насіння трипіда. При активації пастки ціль знерухомлюється, її здатність до ухилення знижується. Час дії: [%e1.SummonTrap.SummonTime] Радіус дії: 5 м. Потрібна стигма.",
		"ra_trackermind": "[%e1.WeaponStatUp.StatName] +[%e1.WeaponStatUp.Value]%%. Зброя: [%e1.WeaponStatUp.WeaponCategory]. Під час дії вміння витрата МР збільшується на 10%%. Активне вміння Потрібна стигма.",
		"ri_bindingslam": "Удар магією вітру, завдає цілі [%e1.SpellATK_Instant.FixDamage] од. шкоди та скуто її. Час дії: [%e2.Root.RemainTime]. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ri_chainfire": "Удар магією вогню, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. 2 повтори 2-е вміння в серії Вогняний шквал - Безперервний вогонь Потрібна стигма.",
		"ri_eathiumblast": "Удар магією повітря, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ri_eathiumblast_2": "Удар магією повітря, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м.",
		"ri_eathiumblast_3": "Удар магією повітря, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі та максимум 6 сусупротивникам, що знаходяться на відстані до 5 м від неї. Радіус дії: [%First_Target_Valid_Distance] м.",
		"ri_eathiumcompress": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]. [%e1.StatUp.StatName3] +[%e1.StatUp.Value3]. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"ri_eathiumcurtain": "Захищає від наступної магічної атаки 1 раз або 1 раз парирує фізичну атаку. Час дії: [%e1.AlwaysResist.RemainTime] Потрібна стигма.",
		"ri_eathiumreactive": "Відновлює [%e1.MpHeal_Instant.Heal] MP. Потрібна стигма.",
		"ri_eathiumreactive_2": "Відновлює [%e1.MpHeal_Instant.Heal] MP.",
		"ri_eathiumreactive_3": "Відновлює [%e1.MpHeal_Instant.Heal] MP.",
		"ri_eathiumwall": "Створює захисний бар'єр, з ймовірністю [%e1.MPShield.ConditionProb]%% блокуючий [%e1.MPShield.CoverValue]%% шкоди. Необхідна умова: [%e1.MPShield.Condition]. Час дії: 30 сек. Захисний бар'єр зберігається до завдання персонажу [%e1.MPShield.ShieldValue] од. шкоди. Також витрачає [%e1.MPShield.LoseMP]%% MP в залежності від отриманої шкоди. Під час дії захисного бар'єра опір шоку +[%e2.StatUp.Value], [%e2.StatUp.StatName2] +[%e2.StatUp.Value2], а опір до сну -[%e3.StatDown.Value]. Активне вміння Потрібна стигма.",
		"ri_flamethrow": "Удар магією повітря, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди максимум 3 ворогам в радіусі 15 м від передньої півсфери. Потрібна стигма.",
		"ri_flamethrow_2": "Удар магією повітря, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди максимум 4 ворогам в радіусі 15 м від передньої півсфери та з певним шансом оглушає їх.",
		"ri_flamethrow_3": "Удар магією повітря, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди максимум 6 ворогам в радіусі 15 м від передньої півсфери та з певним шансом оглушає їх.",
		"ri_forwardstrike": "Атака магією води, завдає цілям в радіусі 15 м від передньої півсфери [%e1.SpellATK_Instant.FixDamage] од. шкоди. 2-е вміння в серії Охолоджуючий удар - Руйнівна хвиля Потрібна стигма.",
		"ri_itheumreflector": "При кожному отриманні шкоди забирає [%e1.Provoker.OtherSkill.e1.MPAttack_Instant.Damage] MP цілі. Час дії: [%e1.Provoker.RemainTime] Потрібна стигма.",
		"ri_magneticfield": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Стійкість до оглушення, заборони на використання фізичних умінь та страху +[%e2.StatUp.Value]. Знижує шкоду, отримувану в PvP. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"ri_overcharge": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%%. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]. Завдає додаткової шкоди в PvP. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"ri_poweroverdrive": "Знімає з персонажа накладені ефекти зниження швидкості атаки. На 30 сек. опір шоку +[%e1.StatUp.Value], [%e1.StatUp.StatName2] +[%e1.StatUp.Value2], опір негативним ефектам переміщення +[%e2.StatUp.Value]. Активне вміння Потрібна стигма.",
		"ri_powerslam": "Удар магією вогню, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ri_rapidattack": "Атака магією землі, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. 3 повтори 2-е вміння в серії Дроблячий удар - Град атак Потрібна стигма.",
		"ri_rapidcharge": "Відновлює [%e2.Heal_Instant.Heal] HP та [%e1.MPHeal_Instant.Heal] MP. Потрібна стигма.",
		"ri_shielddestroyer": "Удар магією землі, завдає цілі [%e1.SpellATK_Instant.FixDamage] од. шкоди, оглушає її та знімає захисні ефекти. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"ri_speedoverdrive": "Швидкість пересування і польоту +[%e1.StatUp.Value]%%. [%e3.StatUp.StatName] +[%e3.Statup.Value]. [%e2.StatDown.StatName] -[%e2.StatDown.Value]. [%e2.StatDown.StatName3] -[%e2.StatDown.Value3]. Час дії: 10 сек. Активне вміння Потрібна стигма.",
		"ri_tunesensor": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"ri_weaponsmash": "Удар магією повітря, завдає цілі в радіусі [%First_Target_Valid_Distance] м [%e1.SpellATK_Instant.FixDamage] од. шкоди. При цьому її [%e2.StatDown.StatName] -[%e2.StatDown.Value], [%e2.StatDown.StatName2] -[%e2.StatDown.Value2]. Час дії: [%e2.StatDown.RemainTime] Потрібна стигма.",
		"sc_trueshotmind": "[%e1.OneTimeBoostSkillAttack.AttackType] +[%e1.OneTimeBoostSkillAttack.BonusRate]%%. Кількість атак: [%e1.OneTimeBoostSkillAttack.AttackCount]. Час дії: [%e1.OneTimeBoostSkillAttack.RemainTime] [%e2.StatDown.StatName] -[%e2.StatDown.Value]%%. Потрібна стигма.",
		"wa_gatecrush": "Фізична атака, завдає цілі [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] од. шкоди. Якщо ціль - ворота, то додатково завдає [%e1.SkillATK_Instant.AddDamage] од. шкоди. Потрібна стигма.",
		"wa_steadiness": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"wi_arcaneboost": "Зменшує час підготовки магічних умінь на [%e1.BoostSkillCastingTime.CastingBonus]%%. Час дії: [%e1.BoostSkillCastingTime.RemainTime] Потрібна стигма.",
		"wi_arcanepower": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"wi_arcanewisdom": "Знижує витрати MP на [%e1.BoostSkillCost.BonusRate]%%. Час дії: [%e1.BoostSkillCost.RemainTime] Потрібна стигма.",
		"wi_countermagic": "Кожного разу, коли ціль використовує магічні вміння, вона завдає собі [%e1.MagicCounterATK.Damage]%% шкоди від своїх макс. HP. Радіус дії: [%First_Target_Valid_Distance] м. (Завдана шкода не може перевищувати [%e1.MagicCounterATK.MaxDamage].) Час дії: [%e1.MagicCounterATK.RemainTime] Потрібна стигма.",
		"wi_cursedtree": "Перетворює ціль на дерево. Час дії: [%e1.Deform.RemainTime] В перетвореному стані ціль не може пересуватися і виконувати будь-які дії. [%e3.StatUp.StatName] цілі збільшується. Ефект зникає при отриманні шкоди. Потрібна стигма.",
		"wi_cyclonestrike": "Удар магією повітря, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"wi_deepsleep": "Усипляє ціль. [%e3.StatUp.StatName] збільшується. Час дії: [%e2.Sleep.RemainTime] Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"wi_deepsleep_2": "Усипляє ціль. [%e3.StatUp.StatName] збільшується. Час дії: [%e2.Sleep.RemainTime] Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"wi_deepsleep_3": "Усипляє ціль. [%e3.StatUp.StatName] збільшується. Час дії: [%e2.Sleep.RemainTime] Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"wi_elementalseal": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"wi_flamestrike": "Удар магією вогню, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"wi_frostpillar_dark": "Удар магією води, протягом 20 сек. завдає шкоду в певному радіусі максимум 8 сусупротивникам, знижуючи їх швидкість руху. Потрібна стигма.",
		"wi_frostpillar_light": "Удар магією води, протягом 20 сек. завдає шкоду в певному радіусі максимум 8 сусупротивникам, знижуючи їх швидкість руху. Потрібна стигма.",
		"wi_hibernation": "Заморожує ціль в радіусі [%First_Target_Valid_Distance] м, оглушаючи її і роблячи нечутливою до атак. Час дії: [%e1.stun.RandomTime]-[%e1.stun.RemainTime] Потрібна стигма.",
		"wi_hpmpexchange": "Міняє місцями ваші MP та HP. Потрібна стигма.",
		"wi_icebarrier": "Створює захисний бар'єр, що поглинає [%e1.Shield.CoverValue] од. шкоди. Необхідна умова: [%e1.Shield.Condition] на персонажа. Час дії: [%e1.Shield.RemainTime] Ви оглушені на час дії цього вміння. Потрібна стигма.",
		"wi_icyshield": "Відбиває [%e1.Reflector.FixedDamage] од. шкоди у ворога в радіусі [%e1.Reflector.MaxRange] м. Необхідна умова: [%e1.Reflector.Condition]. Час дії: [%e1.Reflector.RemainTime] Швидкість руху та атаки ворога зменшується. Час дії: [%e2.Provoker.OtherSkill.e1.Snare.RemainTime] Потрібна стигма.",
		"wi_icyveins_dark": "Зменшує час підготовки вмінь на [%e1.BoostSkillCastingTime.CastingBonus]%%. Час дії: [%e1.BoostSkillCastingTime.RemainTime] Потрібна стигма.",
		"wi_icyveins_light": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"wi_illusiondance": "Знімає з вас 1 фізичний негативний ефект і дозволяє ухилитися від фізичних атак. Кількість ухилень: [%e2.AlwaysDodge.Count]. Час дії: [%e2.AlwaysDodge.RemainTime] Потрібна стигма.",
		"wi_illusionstorm": "Магічна атака вогнем, завдає 6 цілям в радіусі 10 м [%e1.SpellATK_Instant.FixDamage] од. шкоди. Ступорить сусупротивника на [%e2.Stun.RemainTime] Потрібна стигма.",
		"wi_massexplosion": "Удар магією вогню, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди цілі в радіусі [%First_Target_Valid_Distance] м від вашого персонажа та 6 сусупротивникам в радіусі 5 м від вибраної цілі. Потрібна стигма.",
		"wi_rockfall": "Удар магією землі, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"wi_sleepingstorm": "Усипляє ціль в радіусі [%First_Target_Valid_Distance] м від персонажа і 6 сусупротивників в радіусі 12 м навколо неї. [%e2.StatUp.StatName] сусупротивників в зоні дії вміння збільшується. Час дії: [%e1.Sleep.RemainTime] Потрібна стигма.",
		"wi_soulgain": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Час дії: [%e1.StatUp.RemainTime] Потрібна стигма.",
		"wi_stigma_atomicenergy_dark": "Стигма давнього даєва. Удар магією вогню, через [%e1.DelayedSpellATK_Instant.DelayedTime] завдає [%e1.DelayedSpellATK_Instant.Damage] од. шкоди меті, що знаходиться на відстані не більше [%First_Target_Valid_Distance] м, і 6 сусупротивникам в радіусі 10 м від неї. Потрібна стигма.",
		"wi_stigma_atomicenergy_light": "Стигма давнього даєва. Удар магією вогню, через [%e1.DelayedSpellATK_Instant.DelayedTime] завдає [%e1.DelayedSpellATK_Instant.Damage] од. шкоди меті, що знаходиться на відстані не більше [%First_Target_Valid_Distance] м, і 6 сусупротивникам в радіусі 10 м від неї. Потрібна стигма.",
		"wi_stigma_icelance": "Удар магією води, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"wi_stigma_lavawave_dark": "Удар магією вогню, через [%e1.DelayedSpellATK_Instant.DelayedTime] завдає [%e1.DelayedSpellATK_Instant.Damage] од. шкоди цілі, що знаходиться на відстані не більше [%First_Target_Valid_Distance] м, та 6 супротивникам в радіусі 10 м від неї. Потрібна стигма.",
		"wi_stigma_volcanicflame_light": "Удар магією вогню, через [%e1.DelayedSpellATK_Instant.DelayedTime] завдає [%e1.DelayedSpellATK_Instant.Damage] од. шкоди цілі, що знаходиться на відстані не більше [%First_Target_Valid_Distance] м, та 6 супротивникам в радіусі 10 м від неї. Потрібна стигма.",
		"wi_stormshock": "Магічна атака вітром, завдає цілі [%e1.SpellATK_Instant.FixDamage] од. шкоди та на деякий час оглушає її. Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"wi_summontornado_dark": "З'являється поруч з ціллю, що знаходиться в радіусі [%First_Target_Valid_Distance] м, завдає шкоди магією повітря максимум 6 ворогам в межах 10 м, на короткий час викликає оглушуюче торнадо. Час дії: [%e1.SummonSkillArea.SummonTime] Потрібна стигма.",
		"wi_summontornado_light": "З'являється поруч з ціллю, що знаходиться в радіусі [%First_Target_Valid_Distance] м, завдає шкоди магією повітря максимум 6 ворогам в межах 10 м, на короткий час викликає оглушуюче торнадо. Час дії: [%e1.SummonSkillArea.SummonTime] Потрібна стигма.",
		"wi_wakeup": "Пробуджує ціль в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"wi_windcutter": "Магічна атака вітром, завдає цілі [%e1.SpellATK_Instant.FixDamage] од. шкоди і викликає кровотечу. Час дії: [%e2.Bleed.RemainTime] Радіус дії: [%First_Target_Valid_Distance] м. Потрібна стигма.",
		"wi_zeropoint": "Удар магією води, завдає [%e1.SpellATK_Instant.FixDamage] од. шкоди в радіусі [%First_Target_Valid_Distance] м. Потрібна стигма."
	},
	bonusnames: {
		"activedefend": "Ухил, парир., блок",
		"arfear": "Зах. від страху",
		"arparalyze": "Зах. від паралічу",
		"arroot": "Зах. від знерухомлення",
		"arsilence": "Захист від німоти",
		"arsleep": "Зах. від сну",
		"arsnare": "Зах. від сповільнення",
		"arstagger": "Зах. від відштовхування",
		"arstumble": "Зах. від перекидання",
		"arstun": "Зах. від оглушення",
		"arstunlike": "Зах. від шоку",
		"attack": "Атака",
		"attackdelay": "Швидк. атаки",
		"block": "Блок",
		"boostcastingtime": "Швидк. магії",
		"boosthate": "Агресія",
		"concentration": "Концентрація",
		"critical": "Ф. крит.",
		"damage_reduce": "Зниження шкоди",
		"dodge": "Ухилення",
		"elementaldefendair": "Захист від повітря",
		"elementaldefendall": "Захист від усіх стихій",
		"elementaldefendearth": "Захист від землі",
		"elementaldefendfire": "Захист від вогню",
		"elementaldefendwater": "Захист від води",
		"flyspeed": "Швидк. польоту",
		"healskillboost": "Сила зцілення",
		"hitaccuracy": "Точність",
		"hpregen": "Відновлення HP",
		"level": "Рів.",
		"magicalattack": "Маг. атака",
		"magicalcritical": "М. крит.",
		"magicalcriticaldamagereduce": "Захист м. крит.",
		"magicalcriticalreducerate": "Блок м. крит.",
		"magicaldefend": "Маг. захист",
		"magicalhitaccuracy": "Маг. точність",
		"magicalresist": "Маг. опір",
		"magicalskillboost": "Сила магії",
		"magicalskillboostresist": "Опір магії",
		"manastones": "Маг. камені рів. %1",
		"maxfp": "Час польоту",
		"maxhp": "Макс. HP",
		"maxhp_disp": "HP",
		"maxmp": "Макс. MP",
		"mpregen": "Відновлення MP",
		"other": "Інше",
		"paralyze_arp": "Опір паралічу",
		"parry": "Парир.",
		"phyattack": "Атака",
		"physicalcriticaldamagereduce": "Захист ф. крит.",
		"physicalcriticalreducerate": "Блок ф. крит.",
		"physicaldefend": "Захист",
		"pvpattackratio": "Шкода в PvP",
		"pvpattackratio_magical": "Шкода в PvP (маг.)",
		"pvpattackratio_physical": "Шкода в PvP (фіз.)",
		"pvpdefendratio": "Захист в PvP",
		"pvpdefendratio_magical": "Захист в PvP (маг.)",
		"pvpdefendratio_physical": "Захист в PvP (фіз.)",
		"silence_arp": "Опір німоті",
		"speed": "Швидк. руху"
	}
});
