// Українська локалізація калькулятора стигм.
//
// Назви вмінь узято з українського паку Origin (client_strings_skill.xml)
// за іменем рядка STR_..., а не перекладено наново — так вони збігаються
// з тим, що гравець бачить у клієнті.
//
// Файл підключається ПІСЛЯ lang_en.js і перекриває його. Те, чого тут
// немає (описи вмінь, 39 назв класів поза 4.6),
// лишається англійським.

lang = $.extend(true, lang, {
	base: {
		"sec": "с",
		"min": "хв",
		"hour": "год",
		"novalue": "[немає значення]",
		"reqlvl": "Доступно з %1 рівня",
		"shards": "Потрібно шардів: %1",
		"nodesc": "Опису немає",
		"cost": "Вартість уміння",
		"cooltime": "Відкат",
		"casttime": "Час використання",
		"instant": "Миттєво",
		"stage": "Етап %1"
	},
	other: {
		"everyhit": "атака",
		"stumble": "Збивання з ніг",
		"openaerial": "підкидання в повітря",
		"nmlatk": "атака",
		"phhit": "фізична атака",
		"magical": "магічні атаки",
		"attackrange": "Дальність атаки",
		"bow": "Лук",
		"physical": "Фізична атака",
		"pmdefend": "Фізичний захист і захист від усіх стихій",
		"pmattack": "Фізична й магічна атака"
	},
	classes: {
		"all": "Усі класи",
		"assassin": "Вбивця",
		"ranger": "Стрілець",
		"chanter": "Чародій",
		"priest": "Цілитель",
		"fighter": "Гладіатор",
		"knight": "Охоронець",
		"wizard": "Чарівник",
		"elementalist": "Заклинач",
		"bard": "Бард",
		"gunner": "Стрілець-технік",
		"rider": "Вершник"
	},
	abyssranks: {
		"rank_min": "Мін. ранг Безодні: %1",
		"rank_max": "Макс. ранг Безодні: %1",
		"rank1": "Воїн 9 рангу",
		"rank2": "Воїн 8 рангу",
		"rank3": "Воїн 7 рангу",
		"rank4": "Воїн 6 рангу",
		"rank5": "Воїн 5 рангу",
		"rank6": "Воїн 4 рангу",
		"rank7": "Воїн 3 рангу",
		"rank8": "Воїн 2 рангу",
		"rank9": "Воїн 1 рангу",
		"rank10": "Офіцер 1 зірки",
		"rank11": "Офіцер 2 зірок",
		"rank12": "Офіцер 3 зірок",
		"rank13": "Офіцер 4 зірок",
		"rank14": "Офіцер 5 зірок",
		"rank15": "Генерал",
		"rank16": "Великий генерал",
		"rank17": "Командувач",
		"rank18": "Правитель"
	},
	'skillnames': {
		"as_assaultslash": "Кровоточивий поріз",
		"as_backblow": "Зворотний руйнівний удар",
		"as_blindingburst": "Туманна завіса",
		"as_blindside": "Засідка",
		"as_carvesignetchain": "Нанесення складного клейма",
		"as_chainsignetburst": "Спалах складного клейма",
		"as_explosionpoison": "Порох",
		"as_flashslash": "Розсікаюча блискавка",
		"as_hitmanmind": "Клятва точності",
		"as_mirrorattack": "Кидок сюрикена",
		"as_quickmove": "Клятва швидкості",
		"as_runnersstance": "Порятунок",
		"as_senseboost": "Обострення почуттів",
		"as_shadowdodge": "Тіньова ілюзія",
		"as_shadowdrop": "Падіння в тінь",
		"as_signetflare": "Знищення печатки",
		"as_signetwave": "Нанесення клейма на відстані",
		"as_silentburst": "Спалах клейма мовчання",
		"as_stabstance": "Готовність",
		"as_stigma_demonicburst_dark": "[Давня стигма] Запалення клейма темряви",
		"as_stigma_moonburst_dark": "Запалення печатки чорного пекла",
		"as_stigma_novaburst_light": "[Давня стигма] Спалах клейма світла",
		"as_stigma_shadowwalk": "Тіньовий крок",
		"as_stigma_sunburst_light": "Спалах печатки небес",
		"as_stunburst": "Блискуча спалах",
		"as_stuningintention": "Застосування смертельних отрут",
		"as_tigerassault": "Чудовиський шрам",
		"as_venomslash": "Клинок обмороку",
		"as_venomstab": "Атака отрутою",
		"as_visiouseye": "Око гніву",
		"as_whisperofgale": "Клятва ухилення",
		"as_windslash": "Стремкий розсікаючий удар",
		"ba_delayparalyze": "Ехо паралічу",
		"ba_focusdefence": "Мотив заліза",
		"ba_lullaby": "Танець жартівника",
		"ba_playingstyleschangea": "Закон зцілення",
		"ba_playingstyleschangeb": "Закон посилення",
		"ba_sanctuary": "Акорд сніжинки",
		"ba_songofbind": "Захоплюючий гуркіт",
		"ba_songofbless": "Мотив звільнення",
		"ba_songofbrave": "Мотив відваги",
		"ba_songofearth": "Бджолиний марш",
		"ba_songoffirm": "Мотив самовладання",
		"ba_songofgale": "Акорд дисгармонії",
		"ba_songofmanareverse": "Рапсодія забуття",
		"ba_songofpain": "Рапсодія мушки",
		"ba_songofregeneration": "Мотив народження",
		"ba_songofresurrection": "Небесний реквієм",
		"ba_songogpeace": "Ноктюрн світу",
		"ch_blessprotect": "Благословення стійкості",
		"ch_chakra": "Відновлення життєвої сили",
		"ch_chant_improvedcritical": "Закляття удачі",
		"ch_chant_improvedresiststun": "Закляття посилення",
		"ch_chant_invincible": "Закляття невразливості",
		"ch_encouragerun": "Натхнення екстазу",
		"ch_healingtank": "Обряд поглинання",
		"ch_heroicstrike": "Фатальний удар",
		"ch_imbuepower": "Благословення вітру",
		"ch_improvedallattack": "Обряд натхнення",
		"ch_improvedalldefend": "Обряд захисту",
		"ch_improvedbody": "Обряд неприступності",
		"ch_improvedlifestream": "Обряд життя",
		"ch_mountaincrash": "Руйнівний удар",
		"ch_mpheal": "Магічне відновлення",
		"ch_nightwish": "Обряд люті",
		"ch_phoenixstep": "Управління небесами",
		"ch_protectself": "Самозахист",
		"ch_shockwave": "Атакуюча хвиля",
		"ch_slowcrash": "Шоковий удар",
		"ch_soaredrock": "Удар землі",
		"ch_splashswing": "Розлючений замах",
		"ch_stigma_angelicwall_light": "Захисний покров",
		"ch_stigma_angelicwish_light": "[Давня стигма] Обряд перешкоди",
		"ch_stigma_demonicwall_dark": "Ефірний покров",
		"ch_stigma_demonicwish_dark": "[Давня стигма] Обряд межі",
		"ch_stigma_recoverword": "Обряд відновлення",
		"ch_surperiorheal": "Длань відновлення",
		"ch_swordbind": "Кидок оков",
		"ch_thruststrike": "Буйство",
		"ch_triplethrust": "Шквал уколів",
		"cl_imbuemana": "Клятва ефіру",
		"el_bind": "Заточення плоті",
		"el_dimisspolymorph": "Атака елементаля",
		"el_drainenergy": "Поглинання життєвої сили",
		"el_earthguardiance": "Охоронець землі",
		"el_elementalboost": "Зцілення розуму",
		"el_elementalcharge": "Посилення елемента: Відновлення",
		"el_elementtransfer": "Перехід енергії",
		"el_enchantarmor": "Посилення елементаля: Посилені обладунки",
		"el_enchantmentburst": "Магічне загоряння",
		"el_enervationcurse": "Прокляття темряви",
		"el_enfeeblement": "Сповільнюючі кайдани",
		"el_escape": "Герб маскування",
		"el_ethercharge": "Посилення елементаля: Відновлення",
		"el_fireaid": "Благословення вогню",
		"el_hellcurse": "Загробне прокляття",
		"el_hellpain": "Невитримувані муки",
		"el_manareverse": "Спалити чари",
		"el_order_elementalfield": "Команда: Стіна захисту",
		"el_order_omen": "Команда: Гіпноз",
		"el_order_protect": "Команда: Захист",
		"el_order_sacrifice": "Команда: Заміна",
		"el_silence": "Блокування магії",
		"el_sleepingspirit": "Узи сну",
		"el_soulsteal": "Крадіжка душі",
		"el_stigma_order_destructimpact": "Команда: Руйнівна атака",
		"el_stigma_order_etheremission_light": "[Давня стигма] Команда: Жертва",
		"el_stigma_order_ethereruption_light": "Команда: Спалити дотла",
		"el_stigma_order_etherimpact_dark": "[Давня стигма] Команда: Самознищення",
		"el_stigma_order_shadoweruption_dark": "Команда: Спалах",
		"el_stigma_stormblade": "Ураган гніву",
		"el_sympatheticswitch": "Жертва елементаля",
		"el_terrorspirit": "Вопль жаху",
		"fi_anklegrab": "Захоплення ніг",
		"fi_anklesnatcher": "Зв'язування ніг",
		"fi_berserkstance": "Стійка берсерка",
		"fi_blademode": "Підготовка до бою",
		"fi_burserklance": "Затоптування",
		"fi_charginghit": "Руйнівний удар",
		"fi_chargingshock": "Знищувальний удар",
		"fi_cripplingcut": "Нисхідний удар",
		"fi_drainsword": "Меч вампіра",
		"fi_enfeeblehit": "Виснажливий удар",
		"fi_heavyimpact": "Хвиля землетрусу",
		"fi_howling": "Загрозливий рев",
		"fi_jumpattack": "Удар з повітря",
		"fi_kneecrash": "Різка ніг",
		"fi_lockdownimpact": "Ізоляція",
		"fi_magicalbarrier": "Захист маг.енергією",
		"fi_potentialhealth": "Оздоровлення",
		"fi_ragespirit": "Безстрашність",
		"fi_revengeslash": "Удар помсти",
		"fi_seismicdrain": "Вампірська хвиля",
		"fi_sharpnesshit": "Колючий удар",
		"fi_spinningparry": "Концентрація на розвороті",
		"fi_stigma_draincut": "Випити крові",
		"fi_stigma_forceblast_light": "[Давня стигма] Ударна міць меча",
		"fi_stigma_forceburst_light": "Бійня",
		"fi_stigma_shockburst_dark": "Різанина",
		"fi_stigma_shockimpulse_dark": "[Давня стигма] Хвиля бойового безумства",
		"fi_survivorstance": "Друге дихання",
		"fi_technicalcounter": "Майстер контратаки",
		"fi_vorpalhit": "Рубаючий удар",
		"fi_whirldrain": "Виснажуюча хвиля",
		"fi_whirltornado": "Відновлювальна хвиля",
		"gu_antigravitycannon": "Сковуюче ядро",
		"gu_armorbreak": "Ядро розлому",
		"gu_bullseye": "Сфокусованість",
		"gu_empowerammo": "Посилення магічного вибуху",
		"gu_empowermagic": "Мудрість магії",
		"gu_firechainrefresh": "Зарядка магічного вибуху",
		"gu_icecannon": "Удар замороження",
		"gu_magicalbreathing": "Магічне дихання",
		"gu_mentalsnatcher": "Поглинаючий постріл",
		"gu_onepointrapidfire": "Швидкий постріл",
		"gu_rapidstance": "Прискорення стрільби",
		"gu_silenceshot": "Заряд німоти",
		"gu_sunningshot": "Приголомшливий постріл",
		"gu_survivalinstinct": "Інстинкт життя",
		"gu_veinsnipe": "Проникаючий постріл",
		"kn_absolutescare": "Крик жаху",
		"kn_brainstorm": "Руйнування свідомості",
		"kn_breakpower": "Підсічка",
		"kn_conquestmind": "Здатність відновлення",
		"kn_destructshield": "Щит руйнування",
		"kn_destructwish": "Жага руйнування",
		"kn_divinepower": "Збурення",
		"kn_divineslash": "Покарання",
		"kn_executionalstrike": "Усувальний удар",
		"kn_fortitudewave": "Хвиля оков",
		"kn_grandprotection": "Захист союзників",
		"kn_highprovoke": "Виклик гніву",
		"kn_holywrath": "Охоронний щит",
		"kn_intimidation": "Загроза",
		"kn_invinsibleprotect": "Захист богів",
		"kn_invinsibleshield": "Міцний щит",
		"kn_massiveprovoke": "Знущальний регіт",
		"kn_movingstance": "Нижня захист",
		"kn_powersink": "Руйнівний магічний удар",
		"kn_recover": "Реанімація",
		"kn_reflectshield": "Відбивна захист",
		"kn_revivaltouch": "Відновлювальна долоня",
		"kn_sentinel": "Броня покровительства",
		"kn_stigma_demonpunishment_dark": "Правосуддя темряви",
		"kn_stigma_drainsword_dark": "[Давня стигма] Правосуддя бога смерті",
		"kn_stigma_godjudgement_light": "[Давня стигма] Правосуддя богів",
		"kn_stigma_godpunishment_light": "Правосуддя світла",
		"kn_stigma_resistarmor": "Захисний блок",
		"kn_stunningsnacher": "Перехоплення",
		"kn_thunderblade": "Розкат грому",
		"kn_triplesnacher": "Ілюзорний захват",
		"p_equip_dual": "Парна зброя: практика",
		"pr_bindingheal": "Цілюще співчуття",
		"pr_blindinglight": "Блік",
		"pr_calllightning": "Розкати грому",
		"pr_coursewound": "Заборона відновлення",
		"pr_firstaid": "Мерехтіння відновлення",
		"pr_graceofgod": "Благословення богів",
		"pr_healershand": "Право на життя",
		"pr_healinggrace": "Покровительство цілителя",
		"pr_massdispel": "Сяйво очищення",
		"pr_massemergentheal": "Сяйво відновлення",
		"pr_memoryblur": "Розсіювання пам'яті",
		"pr_offensivemode": "Право на знищення",
		"pr_painlinks": "Цепка страждань",
		"pr_powersmite": "Правосуддя землі",
		"pr_purgatory": "Натиск землі",
		"pr_regeneraitionshine": "Сяйво регенерації",
		"pr_restorelife": "Рятівна долоня",
		"pr_reversecondition": "Реверс",
		"pr_revivehand": "Відроджуюча долоня",
		"pr_sageswisdom": "Молитва швидкості",
		"pr_sprint": "Різке прискорення",
		"pr_stigma_abysalcircle_dark": "[Давня стигма] Світ Маркутана",
		"pr_stigma_abysalsanctuary_dark": "Сяйво Маркутана",
		"pr_stigma_divinecircle_light": "[Давня стигма] Світло Юстіїля",
		"pr_stigma_divinesanctuary_light": "Сяйво Юстія",
		"pr_stigma_suggestion": "Стійкість",
		"pr_suffermemory": "Ослаблююче клеймо",
		"pr_thunderofpunishment": "Блискавка помсти",
		"pr_tranquility": "Хвиля святості",
		"ra_backdashstab": "Відступ",
		"ra_breathofnature": "Дихання матері-природи",
		"ra_draineye": "Поглинання магії",
		"ra_enchantbow": "Благословенна стріла",
		"ra_explosionarrow": "Розривна стріла",
		"ra_huntermind": "Уловка мисливця",
		"ra_instantsprint": "Миттєвий крок",
		"ra_lightningshot": "Блискавична стріла",
		"ra_marksmanmode": "Приготування до стрільби",
		"ra_massexplosionarrow": "Стріла ярості",
		"ra_movingshot": "Стріла вітру",
		"ra_painarrow": "Стріла страждань",
		"ra_panthermove": "Божевільний вітер",
		"ra_paralyzearrow": "Усипляюча стріла",
		"ra_rapidshot": "Вопляча стріла",
		"ra_resistmind": "Рішучий опір",
		"ra_sealingarrow": "Зв'язуючий постріл",
		"ra_shadowarrow": "Стріла лютого вітру",
		"ra_silentarrow": "Стріла мовчання",
		"ra_spoutarrow": "Злива стріл",
		"ra_stigma_ancientarrow_light": "Стріла Грифонії",
		"ra_stigma_destructarrow_dark": "[Давня стигма] Стріла кондора",
		"ra_stigma_mysticarrow_dark": "Стріла Консіода",
		"ra_stigma_phoenixarrow_light": "[Давня стигма] Стріла грифона",
		"ra_stigma_tigereye": "Тигриний око",
		"ra_trackermind": "Посилення стріл",
		"ri_bindingslam": "Електричні окови",
		"ri_chainfire": "Неперервний вогонь",
		"ri_eathiumblast": "Ідіумова канонада",
		"ri_eathiumcompress": "Магічна компресія",
		"ri_eathiumcurtain": "Захисне поле",
		"ri_eathiumreactive": "Магічна перезарядка",
		"ri_eathiumwall": "Бар'єр іда",
		"ri_flamethrow": "Ідіумове покарання",
		"ri_forwardstrike": "Сокрушуюча хвиля",
		"ri_itheumreflector": "Амортизуюча мембрана",
		"ri_magneticfield": "Енергетичний бар'єр",
		"ri_overcharge": "Максимальна віддача",
		"ri_poweroverdrive": "Підвищення бойової спроможності",
		"ri_powerslam": "Руйнівний прорив",
		"ri_rapidattack": "Град атак",
		"ri_rapidcharge": "Швидка перезарядка",
		"ri_shielddestroyer": "Знищення бар'єрів",
		"ri_speedoverdrive": "Підвищення рухливості",
		"ri_tunesensor": "Регулювання",
		"ri_weaponsmash": "Виснажливий удар",
		"sc_trueshotmind": "Лютий погляд",
		"wa_gatecrush": "Знищення воріт",
		"wa_steadiness": "Броня балансу",
		"wi_arcaneboost": "Мудрість Байзела",
		"wi_arcanepower": "Мудрість Джикела",
		"wi_arcanewisdom": "Мудрість Руміеля",
		"wi_countermagic": "Прокляття слабкості",
		"wi_cursedtree": "Прокляття: Дерево",
		"wi_cyclonestrike": "Штормовий удар",
		"wi_elementalseal": "Стихійний бар'єр",
		"wi_flamestrike": "Ярість вогню",
		"wi_hibernation": "Льодяні окови",
		"wi_hpmpexchange": "Обмін життєвою силою",
		"wi_icebarrier": "Бар'єр розділення",
		"wi_icyshield": "Ледяні обладунки",
		"wi_illusiondance": "Ілюзія",
		"wi_illusionstorm": "Ураган ілюзій",
		"wi_massexplosion": "Вогняна спалах",
		"wi_rockfall": "Призив скелі",
		"wi_sleepingstorm": "Шторм сну",
		"wi_soulgain": "Мольба концентрації",
		"wi_stigma_icelance": "Льодовий гарпун",
		"wi_stormshock": "Падіння блискавки",
		"wi_wakeup": "Скасування сну",
		"wi_windcutter": "Лезо вітру",
		"wi_zeropoint": "Льодовий удар"
	}
});
